using XenonClinic.Core.Enums;
using XenonClinic.Core.Interfaces;

namespace XenonClinic.Core.Entities;

/// <summary>
/// Records a transaction processed through a payment gateway
/// </summary>
public class PaymentGatewayTransaction : IBranchEntity
{
    public int Id { get; set; }

    /// <summary>
    /// Branch ID for multi-tenant data isolation
    /// </summary>
    public int BranchId { get; set; }
    public Branch? Branch { get; set; }

    /// <summary>
    /// Reference to the gateway configuration used
    /// </summary>
    public int GatewayConfigId { get; set; }
    public PaymentGatewayConfig? GatewayConfig { get; set; }

    /// <summary>
    /// Payment gateway provider
    /// </summary>
    public PaymentGatewayProvider Provider { get; set; }

    /// <summary>
    /// Unique transaction reference generated by our system
    /// </summary>
    public string TransactionReference { get; set; } = string.Empty;

    /// <summary>
    /// Transaction ID from the payment gateway
    /// </summary>
    public string? GatewayTransactionId { get; set; }

    /// <summary>
    /// Payment intent ID (Stripe) or Order ID (PayPal)
    /// </summary>
    public string? GatewayPaymentIntentId { get; set; }

    /// <summary>
    /// Charge ID from gateway
    /// </summary>
    public string? GatewayChargeId { get; set; }

    /// <summary>
    /// Current status of the transaction
    /// </summary>
    public PaymentGatewayStatus Status { get; set; } = PaymentGatewayStatus.Pending;

    /// <summary>
    /// Transaction amount in smallest currency unit (cents/fils)
    /// </summary>
    public long AmountInSmallestUnit { get; set; }

    /// <summary>
    /// Transaction amount in decimal
    /// </summary>
    public decimal Amount { get; set; }

    /// <summary>
    /// Currency code (ISO 4217)
    /// </summary>
    public string Currency { get; set; } = "AED";

    /// <summary>
    /// Gateway fee charged
    /// </summary>
    public decimal? GatewayFee { get; set; }

    /// <summary>
    /// Net amount after fees
    /// </summary>
    public decimal? NetAmount { get; set; }

    /// <summary>
    /// Payment method type (card, bank_transfer, wallet, etc.)
    /// </summary>
    public string PaymentMethodType { get; set; } = "card";

    /// <summary>
    /// Card brand if applicable (visa, mastercard, amex, etc.)
    /// </summary>
    public string? CardBrand { get; set; }

    /// <summary>
    /// Last 4 digits of card
    /// </summary>
    public string? CardLast4 { get; set; }

    /// <summary>
    /// Card expiry month
    /// </summary>
    public int? CardExpMonth { get; set; }

    /// <summary>
    /// Card expiry year
    /// </summary>
    public int? CardExpYear { get; set; }

    /// <summary>
    /// Reference to the linked invoice
    /// </summary>
    public int? InvoiceId { get; set; }
    public Invoice? Invoice { get; set; }

    /// <summary>
    /// Reference to the linked sale
    /// </summary>
    public int? SaleId { get; set; }
    public Sale? Sale { get; set; }

    /// <summary>
    /// Reference to the patient
    /// </summary>
    public int? PatientId { get; set; }
    public Patient? Patient { get; set; }

    /// <summary>
    /// Customer email for receipt
    /// </summary>
    public string? CustomerEmail { get; set; }

    /// <summary>
    /// Customer name
    /// </summary>
    public string? CustomerName { get; set; }

    /// <summary>
    /// Description of the payment
    /// </summary>
    public string? Description { get; set; }

    /// <summary>
    /// Error code if failed
    /// </summary>
    public string? ErrorCode { get; set; }

    /// <summary>
    /// Error message if failed
    /// </summary>
    public string? ErrorMessage { get; set; }

    /// <summary>
    /// Raw response from gateway (JSON)
    /// </summary>
    public string? GatewayResponse { get; set; }

    /// <summary>
    /// Refunded amount (if any)
    /// </summary>
    public decimal RefundedAmount { get; set; }

    /// <summary>
    /// Refund transaction IDs (JSON array)
    /// </summary>
    public string? RefundTransactionIds { get; set; }

    /// <summary>
    /// IP address of the payer
    /// </summary>
    public string? IpAddress { get; set; }

    /// <summary>
    /// User agent of the payer
    /// </summary>
    public string? UserAgent { get; set; }

    /// <summary>
    /// 3D Secure authentication status
    /// </summary>
    public string? ThreeDSecureStatus { get; set; }

    /// <summary>
    /// Metadata as JSON
    /// </summary>
    public string? Metadata { get; set; }

    // Audit fields
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime? ProcessedAt { get; set; }
    public DateTime? CompletedAt { get; set; }
    public DateTime? UpdatedAt { get; set; }
}
