/**
 * Business & Additional Specialty Demo Data
 * Marketing, Sales, Inventory, Physiotherapy, Neurology, Ophthalmology
 */

// ============================================
// HELPER FUNCTIONS
// ============================================

const getDateString = (daysFromNow: number): string => {
  const date = new Date();
  date.setDate(date.getDate() + daysFromNow);
  return date.toISOString().split("T")[0];
};

const getDateTime = (daysFromNow: number, hour: number): string => {
  const date = new Date();
  date.setDate(date.getDate() + daysFromNow);
  date.setHours(hour, 0, 0, 0);
  return date.toISOString();
};

// ============================================
// MARKETING DEMO DATA
// ============================================

export const marketingData = {
  campaigns: [
    {
      id: 1,
      campaignCode: "CAMP-2024-001",
      name: "Winter Wellness Package",
      description: "Comprehensive health screening package with 20% discount",
      type: "email",
      status: "active",
      startDate: getDateString(-30),
      endDate: getDateString(30),
      budget: 15000,
      actualSpend: 8500,
      targetLeads: 200,
      targetConversions: 50,
      leadsGenerated: 145,
      conversions: 38,
      revenue: 95000,
      targetAudience: "Adults 40+, existing patients due for checkup",
      subject: "Your Winter Health Check Awaits - 20% Off",
      callToAction: "Book Now",
      branchId: 1,
      assignedToUserName: "Marketing Team",
      createdBy: "Admin",
      createdAt: getDateString(-35),
    },
    {
      id: 2,
      campaignCode: "CAMP-2024-002",
      name: "Ramadan Health Awareness",
      description: "Special Ramadan health tips and fasting-safe checkups",
      type: "social",
      status: "completed",
      startDate: getDateString(-90),
      endDate: getDateString(-60),
      budget: 10000,
      actualSpend: 9200,
      targetLeads: 150,
      targetConversions: 40,
      leadsGenerated: 178,
      conversions: 52,
      revenue: 78000,
      targetAudience:
        "All demographics, focus on diabetic and cardiac patients",
      branchId: 1,
      createdBy: "Admin",
      createdAt: getDateString(-95),
    },
    {
      id: 3,
      campaignCode: "CAMP-2024-003",
      name: "Children's Vaccination Drive",
      description:
        "Back to school vaccination and health screening for children",
      type: "event",
      status: "scheduled",
      startDate: getDateString(15),
      endDate: getDateString(45),
      budget: 8000,
      targetLeads: 100,
      targetConversions: 80,
      leadsGenerated: 0,
      conversions: 0,
      targetAudience: "Parents with children aged 4-16",
      branchId: 1,
      createdBy: "Admin",
      createdAt: getDateString(-5),
    },
    {
      id: 4,
      campaignCode: "CAMP-2024-004",
      name: "Corporate Wellness Program",
      description: "B2B outreach for corporate health programs",
      type: "digital",
      status: "active",
      startDate: getDateString(-14),
      endDate: getDateString(76),
      budget: 25000,
      actualSpend: 5000,
      targetLeads: 50,
      targetConversions: 15,
      leadsGenerated: 23,
      conversions: 5,
      revenue: 125000,
      targetAudience: "HR managers, corporate decision makers",
      branchId: 1,
      createdBy: "Admin",
      createdAt: getDateString(-20),
    },
    {
      id: 5,
      campaignCode: "CAMP-2024-005",
      name: "Hearing Aid Referral Program",
      description: "Existing patient referral program with rewards",
      type: "referral",
      status: "active",
      startDate: getDateString(-60),
      budget: 5000,
      actualSpend: 2800,
      targetLeads: 30,
      targetConversions: 20,
      leadsGenerated: 28,
      conversions: 18,
      revenue: 216000,
      targetAudience: "Existing audiology patients",
      branchId: 1,
      createdBy: "Admin",
      createdAt: getDateString(-65),
    },
  ],
  leads: [
    {
      id: 1,
      leadCode: "LEAD-2024-001",
      firstName: "Abdullah",
      lastName: "Al Mazrouei",
      fullName: "Abdullah Al Mazrouei",
      email: "abdullah.mazrouei@company.ae",
      phoneNumber: "+971501234567",
      mobileNumber: "+971551234567",
      companyName: "Emirates Trading LLC",
      jobTitle: "HR Director",
      city: "Dubai",
      country: "UAE",
      status: "qualified",
      source: "campaign",
      sourceDetails: "Corporate Wellness Program campaign",
      interestedIn: "Corporate health packages for 150 employees",
      leadScore: 85,
      priority: "high",
      campaignId: 4,
      campaignName: "Corporate Wellness Program",
      branchId: 1,
      assignedToUserName: "Sales Team",
      nextFollowUpDate: getDateString(2),
      nextFollowUpNotes: "Send customized proposal",
      lastContactedDate: getDateString(-1),
      contactAttempts: 3,
      estimatedValue: 75000,
      notes: "Very interested, needs board approval",
      createdBy: "System",
      createdAt: getDateString(-10),
    },
    {
      id: 2,
      leadCode: "LEAD-2024-002",
      firstName: "Maryam",
      lastName: "Al Hashimi",
      fullName: "Maryam Al Hashimi",
      email: "maryam.h@email.com",
      phoneNumber: "+971502345678",
      status: "new",
      source: "website",
      sourceDetails: "Contact form - hearing consultation",
      interestedIn: "Hearing test and hearing aids",
      leadScore: 60,
      priority: "medium",
      branchId: 1,
      nextFollowUpDate: getDateString(1),
      contactAttempts: 1,
      estimatedValue: 25000,
      createdBy: "System",
      createdAt: getDateString(-2),
    },
    {
      id: 3,
      leadCode: "LEAD-2024-003",
      firstName: "Rashid",
      lastName: "Bin Saeed",
      fullName: "Rashid Bin Saeed",
      phoneNumber: "+971503456789",
      status: "contacted",
      source: "referral",
      sourceDetails: "Referred by patient Ahmed Al Maktoum",
      interestedIn: "Orthopedic consultation - knee pain",
      leadScore: 70,
      priority: "medium",
      campaignId: 5,
      branchId: 1,
      lastContactedDate: getDateString(-3),
      contactAttempts: 2,
      estimatedValue: 5000,
      notes: "Prefers weekend appointments",
      createdBy: "System",
      createdAt: getDateString(-7),
    },
    {
      id: 4,
      leadCode: "LEAD-2024-004",
      firstName: "Fatima",
      lastName: "Al Qasimi",
      fullName: "Fatima Al Qasimi",
      email: "fatima.qasimi@email.com",
      phoneNumber: "+971504567890",
      status: "converted",
      source: "walk_in",
      interestedIn: "Full body checkup",
      leadScore: 90,
      priority: "high",
      campaignId: 1,
      branchId: 1,
      lastContactedDate: getDateString(-14),
      contactAttempts: 2,
      convertedDate: getDateString(-14),
      convertedToPatientId: 10,
      estimatedValue: 2500,
      actualValue: 2800,
      createdBy: "System",
      createdAt: getDateString(-20),
    },
    {
      id: 5,
      leadCode: "LEAD-2024-005",
      firstName: "Omar",
      lastName: "Al Suwaidi",
      fullName: "Omar Al Suwaidi",
      email: "omar.suwaidi@company.ae",
      phoneNumber: "+971505678901",
      companyName: "Dubai Holdings",
      status: "negotiating",
      source: "social_media",
      sourceDetails: "LinkedIn inquiry",
      interestedIn: "Executive health program",
      leadScore: 75,
      priority: "high",
      branchId: 1,
      assignedToUserName: "Sales Team",
      nextFollowUpDate: getDateString(3),
      lastContactedDate: getDateString(-2),
      contactAttempts: 4,
      estimatedValue: 15000,
      notes: "Comparing with other providers",
      createdBy: "System",
      createdAt: getDateString(-15),
    },
    {
      id: 6,
      leadCode: "LEAD-2024-006",
      firstName: "Aisha",
      lastName: "Mohammad",
      fullName: "Aisha Mohammad",
      phoneNumber: "+971506789012",
      status: "lost",
      source: "advertising",
      sourceDetails: "Google Ads - hearing aids",
      interestedIn: "Hearing aids for father",
      leadScore: 45,
      priority: "low",
      branchId: 1,
      lastContactedDate: getDateString(-30),
      contactAttempts: 5,
      lostReason: "Chose competitor - price sensitive",
      createdBy: "System",
      createdAt: getDateString(-45),
    },
  ],
  activities: [
    {
      id: 1,
      activityType: "call",
      subject: "Initial qualification call",
      description: "Discussed corporate wellness needs",
      activityDate: getDateTime(-1, 10),
      durationMinutes: 25,
      status: "completed",
      outcome: "Qualified - scheduling proposal meeting",
      leadId: 1,
      leadName: "Abdullah Al Mazrouei",
      campaignId: 4,
      branchId: 1,
      performedByUserName: "Sales Team",
      contactedPerson: "Abdullah Al Mazrouei",
      nextSteps: "Send proposal by Friday",
      followUpDate: getDateString(2),
      createdBy: "Sales Team",
      createdAt: getDateTime(-1, 10),
    },
    {
      id: 2,
      activityType: "email",
      subject: "Welcome email sent",
      description: "Sent introduction email with clinic brochure",
      activityDate: getDateTime(-2, 14),
      status: "completed",
      outcome: "Email opened, no response yet",
      leadId: 2,
      leadName: "Maryam Al Hashimi",
      branchId: 1,
      performedByUserName: "Marketing Team",
      email: "maryam.h@email.com",
      createdBy: "Marketing Team",
      createdAt: getDateTime(-2, 14),
    },
    {
      id: 3,
      activityType: "meeting",
      subject: "Corporate proposal presentation",
      description: "Present customized wellness package to Emirates Trading",
      activityDate: getDateTime(3, 11),
      durationMinutes: 60,
      status: "scheduled",
      leadId: 1,
      leadName: "Abdullah Al Mazrouei",
      campaignId: 4,
      branchId: 1,
      performedByUserName: "Sales Team",
      contactedPerson: "Abdullah Al Mazrouei",
      notes: "Prepare pricing for 150 employees",
      createdBy: "Sales Team",
      createdAt: getDateTime(-1, 11),
    },
    {
      id: 4,
      activityType: "follow_up",
      subject: "Second follow-up call",
      description: "Follow up on hearing consultation interest",
      activityDate: getDateTime(1, 15),
      status: "scheduled",
      leadId: 2,
      leadName: "Maryam Al Hashimi",
      branchId: 1,
      performedByUserName: "Reception",
      createdBy: "System",
      createdAt: getDateTime(0, 9),
    },
    {
      id: 5,
      activityType: "demo",
      subject: "Hearing aid demonstration",
      description: "Demonstrated premium hearing aids to patient's son",
      activityDate: getDateTime(-45, 14),
      durationMinutes: 45,
      status: "completed",
      outcome: "Lost to competitor",
      leadId: 6,
      leadName: "Aisha Mohammad",
      branchId: 1,
      performedByUserName: "Audiologist",
      notes: "Price was main concern",
      createdBy: "Audiologist",
      createdAt: getDateTime(-45, 14),
    },
  ],
};

// ============================================
// SALES DEMO DATA
// ============================================

export const salesData = {
  sales: [
    {
      id: 1,
      invoiceNumber: "SAL-2024-001234",
      saleDate: getDateString(-7),
      dueDate: getDateString(23),
      status: 2, // Completed
      paymentStatus: 2, // Paid
      patientId: 1,
      patientName: "Ahmed Hassan Al Maktoum",
      branchId: 1,
      subTotal: 25000,
      discountPercentage: 10,
      discountAmount: 2500,
      taxPercentage: 5,
      taxAmount: 1125,
      total: 23625,
      paidAmount: 23625,
      balance: 0,
      isFullyPaid: true,
      isOverdue: false,
      notes: "Hearing aid purchase with accessories",
      items: [
        {
          id: 1,
          saleId: 1,
          itemName: "Phonak Audeo Paradise P90-R",
          itemCode: "HA-PHO-P90R",
          quantity: 2,
          unitPrice: 12000,
          subtotal: 24000,
          total: 24000,
          serialNumber: "PHO-2024-001234",
          warrantyEndDate: getDateString(730),
        },
        {
          id: 2,
          saleId: 1,
          itemName: "Hearing Aid Cleaning Kit",
          itemCode: "ACC-CLEAN-KIT",
          quantity: 1,
          unitPrice: 500,
          subtotal: 500,
          total: 500,
        },
        {
          id: 3,
          saleId: 1,
          itemName: "Battery Pack Size 312",
          itemCode: "ACC-BATT-312",
          quantity: 2,
          unitPrice: 250,
          subtotal: 500,
          total: 500,
        },
      ],
      payments: [
        {
          id: 1,
          paymentNumber: "PAY-2024-001234",
          paymentDate: getDateString(-7),
          amount: 23625,
          paymentMethod: 1, // Card
          saleId: 1,
          cardLastFourDigits: "4521",
          receivedBy: "Reception",
          createdAt: getDateString(-7),
        },
      ],
      createdBy: "Dr. Sarah Ahmed",
      createdAt: getDateString(-7),
    },
    {
      id: 2,
      invoiceNumber: "SAL-2024-001235",
      saleDate: getDateString(-3),
      dueDate: getDateString(27),
      status: 1, // Confirmed
      paymentStatus: 1, // Partial
      patientId: 2,
      patientName: "Fatima Khalid Al Nahyan",
      branchId: 1,
      subTotal: 8500,
      taxPercentage: 5,
      taxAmount: 425,
      total: 8925,
      paidAmount: 5000,
      balance: 3925,
      isFullyPaid: false,
      isOverdue: false,
      notes: "Oncology treatment - insurance pending",
      items: [
        {
          id: 4,
          saleId: 2,
          itemName: "Oncology Consultation",
          quantity: 1,
          unitPrice: 800,
          subtotal: 800,
          total: 800,
        },
        {
          id: 5,
          saleId: 2,
          itemName: "Chemotherapy Administration",
          quantity: 1,
          unitPrice: 5500,
          subtotal: 5500,
          total: 5500,
        },
        {
          id: 6,
          saleId: 2,
          itemName: "Laboratory Tests Panel",
          quantity: 1,
          unitPrice: 1200,
          subtotal: 1200,
          total: 1200,
        },
        {
          id: 7,
          saleId: 2,
          itemName: "Supportive Medications",
          quantity: 1,
          unitPrice: 1000,
          subtotal: 1000,
          total: 1000,
        },
      ],
      payments: [
        {
          id: 2,
          paymentNumber: "PAY-2024-001235",
          paymentDate: getDateString(-3),
          amount: 5000,
          paymentMethod: 3, // Insurance
          saleId: 2,
          insuranceCompany: "Oman Insurance",
          insuranceClaimNumber: "CLM-2024-78901",
          receivedBy: "Insurance Desk",
          createdAt: getDateString(-3),
        },
      ],
      createdBy: "Dr. Nadia Al Farsi",
      createdAt: getDateString(-3),
    },
    {
      id: 3,
      invoiceNumber: "SAL-2024-001236",
      saleDate: getDateString(0),
      dueDate: getDateString(30),
      status: 0, // Draft
      paymentStatus: 0, // Pending
      patientId: 5,
      patientName: "Khalid Ibrahim Al Suwaidi",
      branchId: 1,
      subTotal: 1500,
      taxPercentage: 5,
      taxAmount: 75,
      total: 1575,
      paidAmount: 0,
      balance: 1575,
      isFullyPaid: false,
      isOverdue: false,
      items: [
        {
          id: 8,
          saleId: 3,
          itemName: "Emergency Orthopedic Consultation",
          quantity: 1,
          unitPrice: 500,
          subtotal: 500,
          total: 500,
        },
        {
          id: 9,
          saleId: 3,
          itemName: "X-Ray - Left Wrist",
          quantity: 1,
          unitPrice: 350,
          subtotal: 350,
          total: 350,
        },
        {
          id: 10,
          saleId: 3,
          itemName: "Cast Application",
          quantity: 1,
          unitPrice: 650,
          subtotal: 650,
          total: 650,
        },
      ],
      payments: [],
      createdBy: "Dr. Khalid Al Mansouri",
      createdAt: getDateString(0),
    },
  ],
  quotations: [
    {
      id: 1,
      quotationNumber: "QUO-2024-000456",
      quotationDate: getDateString(-5),
      expiryDate: getDateString(25),
      status: 1, // Sent
      patientId: 3,
      patientName: "Mohammed Rashid Al Falasi",
      branchId: 1,
      subTotal: 35000,
      discountPercentage: 15,
      discountAmount: 5250,
      taxPercentage: 5,
      taxAmount: 1487.5,
      total: 31237.5,
      notes: "Premium hearing aid package - bilateral",
      terms: "Valid for 30 days. 50% advance required.",
      validityDays: 30,
      isExpired: false,
      isActive: true,
      canConvertToSale: true,
      items: [
        {
          id: 1,
          quotationId: 1,
          itemName: "Oticon More 1 miniRITE R",
          itemCode: "HA-OTI-MORE1",
          quantity: 2,
          unitPrice: 14000,
          subtotal: 28000,
          total: 28000,
        },
        {
          id: 2,
          quotationId: 1,
          itemName: "TV Adapter",
          quantity: 1,
          unitPrice: 2000,
          subtotal: 2000,
          total: 2000,
        },
        {
          id: 3,
          quotationId: 1,
          itemName: "Remote Control",
          quantity: 1,
          unitPrice: 1500,
          subtotal: 1500,
          total: 1500,
        },
        {
          id: 4,
          quotationId: 1,
          itemName: "Charger Case",
          quantity: 1,
          unitPrice: 2000,
          subtotal: 2000,
          total: 2000,
        },
        {
          id: 5,
          quotationId: 1,
          itemName: "3-Year Extended Warranty",
          quantity: 1,
          unitPrice: 1500,
          subtotal: 1500,
          total: 1500,
        },
      ],
      createdBy: "Dr. Sarah Ahmed",
      createdAt: getDateString(-5),
    },
    {
      id: 2,
      quotationNumber: "QUO-2024-000457",
      quotationDate: getDateString(-30),
      status: 2, // Accepted
      patientId: 1,
      patientName: "Ahmed Hassan Al Maktoum",
      branchId: 1,
      subTotal: 25000,
      discountPercentage: 10,
      discountAmount: 2500,
      total: 22500,
      validityDays: 30,
      isExpired: false,
      isActive: false,
      canConvertToSale: false,
      acceptedDate: getDateString(-7),
      items: [
        {
          id: 6,
          quotationId: 2,
          itemName: "Phonak Audeo Paradise P90-R (Pair)",
          quantity: 2,
          unitPrice: 12000,
          subtotal: 24000,
          total: 24000,
        },
        {
          id: 7,
          quotationId: 2,
          itemName: "Accessories Package",
          quantity: 1,
          unitPrice: 1000,
          subtotal: 1000,
          total: 1000,
        },
      ],
      createdBy: "Dr. Sarah Ahmed",
      createdAt: getDateString(-30),
    },
  ],
};

// ============================================
// INVENTORY DEMO DATA
// ============================================

export const inventoryData = {
  items: [
    // Hearing Aids
    {
      id: 1,
      itemCode: "HA-PHO-P90R",
      name: "Phonak Audeo Paradise P90-R",
      description: "Premium rechargeable RIC hearing aid with Bluetooth",
      category: 4, // Equipment
      quantity: 12,
      minStockLevel: 4,
      maxStockLevel: 20,
      unitPrice: 12000,
      supplier: "Sonova Gulf LLC",
      location: "Showroom A",
      status: 0, // InStock
      lastRestocked: getDateString(-10),
    },
    {
      id: 2,
      itemCode: "HA-OTI-MORE1",
      name: "Oticon More 1 miniRITE R",
      description: "AI-powered hearing aid with deep neural network",
      category: 4,
      quantity: 8,
      minStockLevel: 4,
      maxStockLevel: 16,
      unitPrice: 14000,
      supplier: "Oticon Middle East",
      location: "Showroom A",
      status: 0,
      lastRestocked: getDateString(-15),
    },
    {
      id: 3,
      itemCode: "HA-SIG-PURE",
      name: "Signia Pure Charge&Go AX",
      description: "Augmented hearing technology with rechargeability",
      category: 4,
      quantity: 6,
      minStockLevel: 4,
      maxStockLevel: 12,
      unitPrice: 11000,
      supplier: "WS Audiology ME",
      location: "Showroom A",
      status: 0,
      lastRestocked: getDateString(-20),
    },
    // Medical Supplies
    {
      id: 4,
      itemCode: "MS-GLOVE-L",
      name: "Nitrile Gloves Large (Box 100)",
      description: "Powder-free nitrile examination gloves",
      category: 0, // Medical
      quantity: 150,
      minStockLevel: 50,
      maxStockLevel: 300,
      unitPrice: 45,
      supplier: "MedSupply UAE",
      location: "Storage Room B",
      status: 0,
      lastRestocked: getDateString(-5),
    },
    {
      id: 5,
      itemCode: "MS-GLOVE-M",
      name: "Nitrile Gloves Medium (Box 100)",
      description: "Powder-free nitrile examination gloves",
      category: 0,
      quantity: 80,
      minStockLevel: 50,
      maxStockLevel: 300,
      unitPrice: 45,
      supplier: "MedSupply UAE",
      location: "Storage Room B",
      status: 0,
      lastRestocked: getDateString(-5),
    },
    {
      id: 6,
      itemCode: "MS-MASK-N95",
      name: "N95 Respirator Masks (Box 20)",
      description: "NIOSH-approved N95 respirator",
      category: 0,
      quantity: 25,
      minStockLevel: 30,
      maxStockLevel: 100,
      unitPrice: 120,
      supplier: "MedSupply UAE",
      location: "Storage Room B",
      status: 1, // LowStock
      lastRestocked: getDateString(-30),
    },
    // Pharmaceuticals
    {
      id: 7,
      itemCode: "PH-PARA-500",
      name: "Paracetamol 500mg (Box 100)",
      description: "Analgesic and antipyretic tablets",
      category: 3, // Pharmaceutical
      quantity: 200,
      minStockLevel: 50,
      maxStockLevel: 400,
      unitPrice: 25,
      supplier: "Gulf Pharma LLC",
      location: "Pharmacy Storage",
      expiryDate: getDateString(365),
      status: 0,
      lastRestocked: getDateString(-7),
    },
    {
      id: 8,
      itemCode: "PH-IBUP-400",
      name: "Ibuprofen 400mg (Box 50)",
      description: "NSAID for pain and inflammation",
      category: 3,
      quantity: 120,
      minStockLevel: 40,
      maxStockLevel: 200,
      unitPrice: 35,
      supplier: "Gulf Pharma LLC",
      location: "Pharmacy Storage",
      expiryDate: getDateString(300),
      status: 0,
      lastRestocked: getDateString(-7),
    },
    {
      id: 9,
      itemCode: "PH-AMOX-500",
      name: "Amoxicillin 500mg (Box 21)",
      description: "Broad-spectrum antibiotic capsules",
      category: 3,
      quantity: 80,
      minStockLevel: 30,
      maxStockLevel: 150,
      unitPrice: 28,
      supplier: "Gulf Pharma LLC",
      location: "Pharmacy Storage",
      expiryDate: getDateString(270),
      status: 0,
      lastRestocked: getDateString(-14),
    },
    // Laboratory Supplies
    {
      id: 10,
      itemCode: "LAB-TUBE-EDTA",
      name: "EDTA Blood Collection Tubes (Box 100)",
      description: "Purple top tubes for hematology",
      category: 2, // Laboratory
      quantity: 40,
      minStockLevel: 50,
      maxStockLevel: 200,
      unitPrice: 180,
      supplier: "Lab Supplies Int'l",
      location: "Lab Storage",
      expiryDate: getDateString(180),
      status: 1, // LowStock
      lastRestocked: getDateString(-45),
    },
    {
      id: 11,
      itemCode: "LAB-TUBE-SST",
      name: "SST Blood Collection Tubes (Box 100)",
      description: "Gold top tubes for serum separation",
      category: 2,
      quantity: 60,
      minStockLevel: 50,
      maxStockLevel: 200,
      unitPrice: 200,
      supplier: "Lab Supplies Int'l",
      location: "Lab Storage",
      expiryDate: getDateString(180),
      status: 0,
      lastRestocked: getDateString(-30),
    },
    // Accessories
    {
      id: 12,
      itemCode: "ACC-BATT-312",
      name: "Hearing Aid Batteries Size 312 (Pack 60)",
      description: "Zinc-air batteries for hearing aids",
      category: 4,
      quantity: 100,
      minStockLevel: 30,
      maxStockLevel: 200,
      unitPrice: 80,
      supplier: "Power Solutions ME",
      location: "Showroom A",
      status: 0,
      lastRestocked: getDateString(-5),
    },
    {
      id: 13,
      itemCode: "ACC-CLEAN-KIT",
      name: "Hearing Aid Cleaning Kit",
      description: "Complete cleaning kit with brush, wax pick, and cloth",
      category: 4,
      quantity: 45,
      minStockLevel: 15,
      maxStockLevel: 80,
      unitPrice: 75,
      supplier: "Universal Hearing Supplies",
      location: "Showroom A",
      status: 0,
      lastRestocked: getDateString(-14),
    },
    // Out of stock item
    {
      id: 14,
      itemCode: "MS-SYRINGE-10",
      name: "Disposable Syringes 10ml (Box 100)",
      description: "Sterile disposable syringes with needle",
      category: 0,
      quantity: 0,
      minStockLevel: 20,
      maxStockLevel: 100,
      unitPrice: 55,
      supplier: "MedSupply UAE",
      location: "Storage Room B",
      status: 2, // OutOfStock
      lastRestocked: getDateString(-60),
    },
  ],
};

// ============================================
// PHYSIOTHERAPY DEMO DATA
// ============================================

export const physiotherapyData = {
  plans: [
    {
      id: 1,
      patientId: 1,
      patientName: "Ahmed Hassan Al Maktoum",
      diagnosis: "ACL reconstruction post-operative rehabilitation",
      goals: [
        "Restore full range of motion",
        "Strengthen quadriceps and hamstrings",
        "Return to sports activities",
      ],
      startDate: getDateString(14), // Post ACL surgery
      totalSessions: 24,
      completedSessions: 0,
      frequency: "3 times per week",
      status: 0, // Active (planned)
      notes: "Protocol to begin 2 weeks post-surgery",
      createdBy: "PT Ahmed",
    },
    {
      id: 2,
      patientId: 2,
      patientName: "Fatima Khalid Al Nahyan",
      diagnosis: "Chronic lower back pain - L4-L5 disc herniation",
      goals: [
        "Reduce pain from 7/10 to 3/10",
        "Improve core stability",
        "Return to daily activities without restriction",
      ],
      startDate: getDateString(-21),
      endDate: getDateString(35),
      totalSessions: 16,
      completedSessions: 8,
      frequency: "2 times per week",
      status: 0, // Active
      notes: "Responding well to McKenzie approach",
      createdBy: "PT Fatima",
    },
    {
      id: 3,
      patientId: 4,
      patientName: "Sara Omar Al Ketbi",
      diagnosis: "Bilateral hip osteoarthritis",
      goals: [
        "Maintain joint mobility",
        "Strengthen hip muscles",
        "Improve walking tolerance",
      ],
      startDate: getDateString(-42),
      totalSessions: 12,
      completedSessions: 10,
      frequency: "2 times per week",
      status: 0,
      notes: "Good progress, considering pool therapy",
      createdBy: "PT Ahmed",
    },
  ],
  sessions: [
    {
      id: 1,
      planId: 2,
      patientId: 2,
      patientName: "Fatima Khalid Al Nahyan",
      sessionDate: getDateString(-3),
      sessionNumber: 8,
      treatments: [
        "Manual therapy",
        "Core stabilization exercises",
        "TENS",
        "Hot pack",
      ],
      painLevelBefore: 5,
      painLevelAfter: 3,
      progressNotes:
        "Improved tolerance to prone exercises. SLR improved to 60°.",
      homeExercises:
        "Continue with core stability exercises 2x daily. Walking 20 min.",
      performedBy: "PT Fatima",
      duration: 45,
    },
    {
      id: 2,
      planId: 2,
      patientId: 2,
      patientName: "Fatima Khalid Al Nahyan",
      sessionDate: getDateString(-7),
      sessionNumber: 7,
      treatments: ["Lumbar mobilization", "Stretching", "McKenzie exercises"],
      painLevelBefore: 6,
      painLevelAfter: 4,
      progressNotes: "Good centralization with repeated extension.",
      homeExercises: "Prone press-ups every 2 hours. Avoid prolonged sitting.",
      performedBy: "PT Fatima",
      duration: 45,
    },
    {
      id: 3,
      planId: 3,
      patientId: 4,
      patientName: "Sara Omar Al Ketbi",
      sessionDate: getDateString(-2),
      sessionNumber: 10,
      treatments: [
        "Hip mobilization",
        "Strengthening exercises",
        "Gait training",
      ],
      painLevelBefore: 4,
      painLevelAfter: 2,
      progressNotes: "Walking distance improved to 500m without rest.",
      homeExercises: "Hip strengthening exercises, daily walking program.",
      performedBy: "PT Ahmed",
      duration: 50,
    },
  ],
  exercisePrograms: [
    {
      id: 1,
      patientId: 2,
      patientName: "Fatima Khalid Al Nahyan",
      planId: 2,
      exercises: [
        {
          name: "Dead Bug",
          sets: 3,
          reps: 10,
          instructions: "Keep lower back flat",
        },
        {
          name: "Bird Dog",
          sets: 3,
          reps: 10,
          holdTime: 5,
          instructions: "Alternate sides",
        },
        {
          name: "Prone Press-up",
          sets: 1,
          reps: 10,
          instructions: "Every 2 hours",
        },
        {
          name: "Cat-Cow Stretch",
          sets: 2,
          reps: 10,
          instructions: "Slow controlled movement",
        },
      ],
      assignedDate: getDateString(-21),
      frequency: "2 times daily",
      notes: "Stop if pain increases or radiates down leg",
      assignedBy: "PT Fatima",
    },
    {
      id: 2,
      patientId: 4,
      patientName: "Sara Omar Al Ketbi",
      planId: 3,
      exercises: [
        {
          name: "Clamshells",
          sets: 3,
          reps: 15,
          instructions: "Use resistance band",
        },
        { name: "Bridging", sets: 3, reps: 12, holdTime: 3 },
        {
          name: "Standing Hip Abduction",
          sets: 3,
          reps: 12,
          instructions: "Hold wall for balance",
        },
        {
          name: "Seated Marching",
          sets: 2,
          reps: 20,
          instructions: "Keep back straight",
        },
      ],
      assignedDate: getDateString(-14),
      frequency: "Daily",
      assignedBy: "PT Ahmed",
    },
  ],
};

// ============================================
// NEUROLOGY DEMO DATA
// ============================================

export const neurologyData = {
  exams: [
    {
      id: 1,
      patientId: 1,
      patientName: "Ahmed Hassan Al Maktoum",
      examDate: getDateString(-30),
      mentalStatus: "alert",
      cranialNerves: "II-XII intact bilaterally",
      motorFunction: "5/5 strength all extremities, normal tone",
      sensory: "Intact to light touch and pinprick throughout",
      reflexes: "2+ symmetric, plantars downgoing",
      coordination: "Finger-nose and heel-shin intact",
      gait: "Normal gait and tandem walk",
      diagnosis: "Normal neurological examination",
      performedBy: "Dr. Neurology",
      status: "completed",
      notes: "Pre-operative clearance for knee surgery",
    },
    {
      id: 2,
      patientId: 6,
      patientName: "Mariam Abdullah Al Mansouri",
      examDate: getDateString(-7),
      mentalStatus: "alert",
      cranialNerves: "VII - mild left facial weakness",
      motorFunction: "4/5 left upper and lower extremity",
      sensory: "Decreased sensation left side",
      reflexes: "2+ right, 3+ left with left Babinski",
      coordination: "Mild left dysmetria",
      gait: "Left-sided weakness, requires assistance",
      diagnosis: "Right MCA territory stroke",
      performedBy: "Dr. Neurology",
      status: "completed",
      notes: "3 weeks post-stroke, starting rehabilitation",
    },
  ],
  eegs: [
    {
      id: 1,
      patientId: 7,
      patientName: "Hassan Ali Al Shamsi",
      recordDate: getDateString(-14),
      duration: 30,
      findings: "epileptic_activity",
      interpretation:
        "Intermittent left temporal sharp waves consistent with focal epilepsy",
      abnormalities: ["Left temporal sharp waves", "Occasional slowing"],
      performedBy: "EEG Tech",
      interpretedBy: "Dr. Neurology",
      status: "interpreted",
      notes: "Correlate with clinical history of seizures",
    },
    {
      id: 2,
      patientId: 8,
      patientName: "Layla Youssef Al Zaabi",
      recordDate: getDateString(-3),
      duration: 25,
      findings: "normal",
      interpretation: "Normal awake and drowsy EEG, no epileptiform activity",
      performedBy: "EEG Tech",
      interpretedBy: "Dr. Neurology",
      status: "interpreted",
      notes: "Follow-up EEG for headaches - reassuring result",
    },
  ],
  epilepsyDiary: [
    {
      id: 1,
      patientId: 7,
      patientName: "Hassan Ali Al Shamsi",
      seizureDate: getDateString(-21),
      seizureType: "focal_impaired_awareness",
      duration: 2,
      triggers: ["Sleep deprivation", "Missed medication"],
      preSymptoms: "Deja vu sensation, feeling of fear",
      postSymptoms: "Confusion for 10 minutes, headache",
      medications: ["Levetiracetam 500mg BID"],
      severity: "moderate",
      notes: "Occurred in the evening, family witnessed",
    },
    {
      id: 2,
      patientId: 7,
      patientName: "Hassan Ali Al Shamsi",
      seizureDate: getDateString(-60),
      seizureType: "focal_to_generalized",
      duration: 3,
      triggers: ["Stress"],
      preSymptoms: "Unusual taste in mouth",
      postSymptoms: "Slept for 2 hours, muscle soreness",
      medications: ["Levetiracetam 500mg BID"],
      severity: "severe",
      notes: "Secondary generalization - reason for EEG",
    },
  ],
  strokeAssessments: [
    {
      id: 1,
      patientId: 6,
      patientName: "Mariam Abdullah Al Mansouri",
      assessmentDate: getDateString(-28),
      nihssScore: 8,
      strokeType: "ischemic",
      affectedArea: "Right middle cerebral artery territory",
      onsetTime: "08:30",
      symptoms: ["Left-sided weakness", "Facial droop", "Slurred speech"],
      treatment: "IV tPA administered within 3 hours",
      performedBy: "Dr. Neurology",
      severity: "moderate",
      recommendations:
        "ICU admission, repeat CT in 24 hours, start aspirin after 24h",
      notes: "Code stroke activated, door-to-needle 45 minutes",
    },
  ],
};

// ============================================
// OPHTHALMOLOGY DEMO DATA
// ============================================

export const ophthalmologyData = {
  visualAcuity: [
    {
      id: 1,
      patientId: 1,
      patientName: "Ahmed Hassan Al Maktoum",
      testDate: getDateString(-14),
      rightEyeUncorrected: "20/40",
      rightEyeCorrected: "20/20",
      leftEyeUncorrected: "20/30",
      leftEyeCorrected: "20/20",
      performedBy: "Optometrist Sara",
      notes: "Requires glasses for distance",
    },
    {
      id: 2,
      patientId: 3,
      patientName: "Mohammed Rashid Al Falasi",
      testDate: getDateString(-7),
      rightEyeUncorrected: "20/200",
      rightEyeCorrected: "20/40",
      leftEyeUncorrected: "20/100",
      leftEyeCorrected: "20/30",
      performedBy: "Optometrist Sara",
      notes: "High myopia, candidate for contact lenses",
    },
  ],
  refractions: [
    {
      id: 1,
      patientId: 1,
      patientName: "Ahmed Hassan Al Maktoum",
      date: getDateString(-14),
      rightSphere: -1.5,
      rightCylinder: -0.75,
      rightAxis: 90,
      leftSphere: -1.25,
      leftCylinder: -0.5,
      leftAxis: 85,
      pupillaryDistance: 64,
      performedBy: "Optometrist Sara",
      notes: "Mild myopia with astigmatism",
    },
    {
      id: 2,
      patientId: 3,
      patientName: "Mohammed Rashid Al Falasi",
      date: getDateString(-7),
      rightSphere: -6.5,
      rightCylinder: -1.25,
      rightAxis: 175,
      leftSphere: -5.75,
      leftCylinder: -1.0,
      leftAxis: 10,
      pupillaryDistance: 66,
      performedBy: "Optometrist Sara",
      notes: "High myopia - discuss LASIK candidacy",
    },
  ],
  iopMeasurements: [
    {
      id: 1,
      patientId: 5,
      patientName: "Khalid Ibrahim Al Suwaidi",
      date: getDateString(-30),
      time: "10:30",
      rightEye: 18,
      leftEye: 17,
      method: "goldmann",
      performedBy: "Dr. Ophthalmology",
      notes: "Within normal limits",
    },
    {
      id: 2,
      patientId: 8,
      patientName: "Layla Youssef Al Zaabi",
      date: getDateString(-7),
      time: "14:00",
      rightEye: 24,
      leftEye: 22,
      method: "goldmann",
      performedBy: "Dr. Ophthalmology",
      notes: "Elevated - repeat measurement, consider glaucoma workup",
    },
  ],
  glassesPrescriptions: [
    {
      id: 1,
      patientId: 1,
      patientName: "Ahmed Hassan Al Maktoum",
      prescriptionDate: getDateString(-14),
      expiryDate: getDateString(351),
      rightSphere: -1.5,
      rightCylinder: -0.75,
      rightAxis: 90,
      rightAdd: 0,
      leftSphere: -1.25,
      leftCylinder: -0.5,
      leftAxis: 85,
      leftAdd: 0,
      pupillaryDistance: 64,
      prescribedBy: "Dr. Ophthalmology",
      type: "distance",
      notes: "Polycarbonate lenses recommended for sports",
    },
    {
      id: 2,
      patientId: 5,
      patientName: "Khalid Ibrahim Al Suwaidi",
      prescriptionDate: getDateString(-60),
      expiryDate: getDateString(305),
      rightSphere: +1.25,
      rightCylinder: -0.25,
      rightAxis: 180,
      rightAdd: 2.0,
      leftSphere: +1.5,
      leftCylinder: -0.5,
      leftAxis: 175,
      leftAdd: 2.0,
      pupillaryDistance: 62,
      prescribedBy: "Dr. Ophthalmology",
      type: "progressive",
      notes: "Progressive lenses for presbyopia",
    },
  ],
};

// ============================================
// EXPORT ALL DATA
// ============================================

export const allBusinessData = {
  marketing: marketingData,
  sales: salesData,
  inventory: inventoryData,
  physiotherapy: physiotherapyData,
  neurology: neurologyData,
  ophthalmology: ophthalmologyData,
};

export default allBusinessData;
