/**
 * Core Modules Demo Data
 * Comprehensive demo data for patients, appointments, multi-tenancy,
 * users, security, payroll structures, and related core modules
 */

import type { Patient } from "../../types/patient";
import type {
  Appointment,
  AppointmentStatus,
  AppointmentType,
} from "../../types/appointment";
import type {
  Tenant,
  Company,
  Branch,
  TenantUser,
  Subscription,
  TenantStatus,
  SubscriptionPlan,
} from "../../types/multi-tenancy";
import type { User } from "../../types/auth";
import type {
  AuditLog,
  UserAccessReview,
  Permission,
  PasswordPolicy,
  SecurityIncident,
  ComplianceReport,
  LoginAttempt,
  Session,
  AuditActionType,
  SecurityAlertSeverity,
} from "../../types/security";
import type {
  SalaryStructure,
  PayrollRecord,
  PayrollStatus,
} from "../../types/payroll";
import type { Employee, EmployeeStatus, EmployeeRole } from "../../types/hr";

// ============================================================
// HELPER FUNCTIONS
// ============================================================

const getDateString = (daysOffset: number): string => {
  const date = new Date();
  date.setDate(date.getDate() + daysOffset);
  return date.toISOString().split("T")[0];
};

const getDateTimeString = (
  daysOffset: number,
  hours = 9,
  minutes = 0,
): string => {
  const date = new Date();
  date.setDate(date.getDate() + daysOffset);
  date.setHours(hours, minutes, 0, 0);
  return date.toISOString();
};

const daysAgo = (days: number) => getDateString(-days);
const daysFromNow = (days: number) => getDateString(days);
const weeksAgo = (weeks: number) => getDateString(-weeks * 7);
const monthsAgo = (months: number) => getDateString(-months * 30);
const yearsAgo = (years: number) => getDateString(-years * 365);

// ============================================================
// PATIENTS MODULE
// ============================================================

const patients: Patient[] = [
  {
    id: 1,
    branchId: 1,
    emiratesId: "784-1985-1234567-1",
    fullNameEn: "Ahmed Hassan Al Maktoum",
    fullNameAr: "أحمد حسن آل مكتوم",
    dateOfBirth: "1985-03-15",
    gender: "M",
    phoneNumber: "+971501234567",
    email: "ahmed.maktoum@email.com",
    hearingLossType: "Sensorineural",
    notes: "Regular patient, bilateral hearing aids",
  },
  {
    id: 2,
    branchId: 1,
    emiratesId: "784-1990-2345678-2",
    fullNameEn: "Fatima Ali Al Nahyan",
    fullNameAr: "فاطمة علي آل نهيان",
    dateOfBirth: "1990-07-22",
    gender: "F",
    phoneNumber: "+971502345678",
    email: "fatima.nahyan@email.com",
    notes: "New patient, referred by Dr. Al Suwaidi",
  },
  {
    id: 3,
    branchId: 1,
    emiratesId: "784-1978-3456789-3",
    fullNameEn: "Mohammed Rashid Al Qasimi",
    fullNameAr: "محمد راشد القاسمي",
    dateOfBirth: "1978-11-08",
    gender: "M",
    phoneNumber: "+971503456789",
    email: "mohammed.qasimi@email.com",
    hearingLossType: "Mixed",
    notes: "History of otitis media, requires annual monitoring",
  },
  {
    id: 4,
    branchId: 2,
    emiratesId: "784-1995-4567890-4",
    fullNameEn: "Sara Ibrahim Al Falasi",
    fullNameAr: "سارة إبراهيم الفلاسي",
    dateOfBirth: "1995-01-30",
    gender: "F",
    phoneNumber: "+971504567890",
    email: "sara.falasi@email.com",
    notes: "Pediatric referral for daughter",
  },
  {
    id: 5,
    branchId: 1,
    emiratesId: "784-1982-5678901-5",
    fullNameEn: "Khalid Omar Al Shamsi",
    fullNameAr: "خالد عمر الشامسي",
    dateOfBirth: "1982-05-12",
    gender: "M",
    phoneNumber: "+971505678901",
    email: "khalid.shamsi@email.com",
    hearingLossType: "Conductive",
    notes: "Post-surgical follow-up patient",
  },
  {
    id: 6,
    branchId: 2,
    emiratesId: "784-1988-6789012-6",
    fullNameEn: "Maryam Yousef Al Mazrouei",
    fullNameAr: "مريم يوسف المزروعي",
    dateOfBirth: "1988-09-25",
    gender: "F",
    phoneNumber: "+971506789012",
    email: "maryam.mazrouei@email.com",
    notes: "Diabetic patient, regular checkups",
  },
  {
    id: 7,
    branchId: 1,
    emiratesId: "784-1970-7890123-7",
    fullNameEn: "Abdullah Saeed Al Ketbi",
    fullNameAr: "عبدالله سعيد الكتبي",
    dateOfBirth: "1970-12-03",
    gender: "M",
    phoneNumber: "+971507890123",
    email: "abdullah.ketbi@email.com",
    hearingLossType: "Presbycusis",
    notes: "Age-related hearing loss, considering hearing aids",
  },
  {
    id: 8,
    branchId: 1,
    emiratesId: "784-2000-8901234-8",
    fullNameEn: "Noura Ahmad Al Suwaidi",
    fullNameAr: "نورة أحمد السويدي",
    dateOfBirth: "2000-04-18",
    gender: "F",
    phoneNumber: "+971508901234",
    email: "noura.suwaidi@email.com",
    notes: "Student, annual wellness checkup",
  },
  {
    id: 9,
    branchId: 2,
    emiratesId: "784-1965-9012345-9",
    fullNameEn: "Hassan Mohammed Al Dhaheri",
    fullNameAr: "حسن محمد الظاهري",
    dateOfBirth: "1965-08-20",
    gender: "M",
    phoneNumber: "+971509012345",
    email: "hassan.dhaheri@email.com",
    hearingLossType: "Profound",
    notes: "Cochlear implant candidate",
  },
  {
    id: 10,
    branchId: 1,
    emiratesId: "784-1992-0123456-0",
    fullNameEn: "Layla Mansoor Al Rumaithi",
    fullNameAr: "ليلى منصور الرميثي",
    dateOfBirth: "1992-02-14",
    gender: "F",
    phoneNumber: "+971500123456",
    email: "layla.rumaithi@email.com",
    notes: "Expecting mother, prenatal care",
  },
];

export const patientsData = {
  patients,
};

// ============================================================
// APPOINTMENTS MODULE
// ============================================================

const appointments: Appointment[] = [
  {
    id: 1,
    patientId: 1,
    branchId: 1,
    providerId: 1,
    startTime: getDateTimeString(0, 9, 0),
    endTime: getDateTimeString(0, 9, 30),
    type: 0 as AppointmentType, // Consultation
    status: 2 as AppointmentStatus, // CheckedIn
    notes: "Annual hearing assessment",
    patient: {
      id: 1,
      fullNameEn: "Ahmed Hassan Al Maktoum",
      phoneNumber: "+971501234567",
    },
    provider: { id: 1, fullName: "Dr. Khalid Mohammed" },
    branch: { id: 1, name: "Main Clinic - Dubai" },
  },
  {
    id: 2,
    patientId: 2,
    branchId: 1,
    providerId: 2,
    startTime: getDateTimeString(0, 10, 0),
    endTime: getDateTimeString(0, 10, 30),
    type: 0 as AppointmentType,
    status: 1 as AppointmentStatus, // Confirmed
    notes: "Initial consultation - new patient",
    patient: {
      id: 2,
      fullNameEn: "Fatima Ali Al Nahyan",
      phoneNumber: "+971502345678",
    },
    provider: { id: 2, fullName: "Dr. Sara Al Ameri" },
    branch: { id: 1, name: "Main Clinic - Dubai" },
  },
  {
    id: 3,
    patientId: 3,
    branchId: 1,
    providerId: 1,
    startTime: getDateTimeString(0, 11, 0),
    endTime: getDateTimeString(0, 11, 45),
    type: 2 as AppointmentType, // Procedure
    status: 0 as AppointmentStatus, // Booked
    notes: "Ear wax removal procedure",
    patient: {
      id: 3,
      fullNameEn: "Mohammed Rashid Al Qasimi",
      phoneNumber: "+971503456789",
    },
    provider: { id: 1, fullName: "Dr. Khalid Mohammed" },
    branch: { id: 1, name: "Main Clinic - Dubai" },
  },
  {
    id: 4,
    patientId: 4,
    branchId: 2,
    providerId: 3,
    startTime: getDateTimeString(0, 14, 0),
    endTime: getDateTimeString(0, 14, 30),
    type: 1 as AppointmentType, // FollowUp
    status: 1 as AppointmentStatus,
    notes: "Post-treatment follow-up",
    patient: {
      id: 4,
      fullNameEn: "Sara Ibrahim Al Falasi",
      phoneNumber: "+971504567890",
    },
    provider: { id: 3, fullName: "Dr. Ahmed Al Hashemi" },
    branch: { id: 2, name: "Branch - Abu Dhabi" },
  },
  {
    id: 5,
    patientId: 5,
    branchId: 1,
    providerId: 2,
    startTime: getDateTimeString(1, 9, 0),
    endTime: getDateTimeString(1, 9, 30),
    type: 0 as AppointmentType,
    status: 0 as AppointmentStatus,
    notes: "Surgical consultation",
    patient: {
      id: 5,
      fullNameEn: "Khalid Omar Al Shamsi",
      phoneNumber: "+971505678901",
    },
    provider: { id: 2, fullName: "Dr. Sara Al Ameri" },
    branch: { id: 1, name: "Main Clinic - Dubai" },
  },
  {
    id: 6,
    patientId: 6,
    branchId: 2,
    providerId: 3,
    startTime: getDateTimeString(1, 10, 0),
    endTime: getDateTimeString(1, 10, 30),
    type: 1 as AppointmentType,
    status: 0 as AppointmentStatus,
    notes: "Diabetes checkup",
    patient: {
      id: 6,
      fullNameEn: "Maryam Yousef Al Mazrouei",
      phoneNumber: "+971506789012",
    },
    provider: { id: 3, fullName: "Dr. Ahmed Al Hashemi" },
    branch: { id: 2, name: "Branch - Abu Dhabi" },
  },
  {
    id: 7,
    patientId: 7,
    branchId: 1,
    providerId: 1,
    startTime: getDateTimeString(-1, 15, 0),
    endTime: getDateTimeString(-1, 15, 45),
    type: 2 as AppointmentType,
    status: 3 as AppointmentStatus, // Completed
    notes: "Hearing aid fitting completed",
    patient: {
      id: 7,
      fullNameEn: "Abdullah Saeed Al Ketbi",
      phoneNumber: "+971507890123",
    },
    provider: { id: 1, fullName: "Dr. Khalid Mohammed" },
    branch: { id: 1, name: "Main Clinic - Dubai" },
  },
  {
    id: 8,
    patientId: 8,
    branchId: 1,
    providerId: 2,
    startTime: getDateTimeString(-2, 11, 0),
    endTime: getDateTimeString(-2, 11, 30),
    type: 0 as AppointmentType,
    status: 4 as AppointmentStatus, // Cancelled
    notes: "Patient requested cancellation",
    patient: {
      id: 8,
      fullNameEn: "Noura Ahmad Al Suwaidi",
      phoneNumber: "+971508901234",
    },
    provider: { id: 2, fullName: "Dr. Sara Al Ameri" },
    branch: { id: 1, name: "Main Clinic - Dubai" },
  },
  {
    id: 9,
    patientId: 9,
    branchId: 2,
    providerId: 3,
    startTime: getDateTimeString(2, 9, 0),
    endTime: getDateTimeString(2, 10, 0),
    type: 3 as AppointmentType, // Emergency
    status: 0 as AppointmentStatus,
    notes: "Urgent evaluation required",
    patient: {
      id: 9,
      fullNameEn: "Hassan Mohammed Al Dhaheri",
      phoneNumber: "+971509012345",
    },
    provider: { id: 3, fullName: "Dr. Ahmed Al Hashemi" },
    branch: { id: 2, name: "Branch - Abu Dhabi" },
  },
  {
    id: 10,
    patientId: 10,
    branchId: 1,
    providerId: 2,
    startTime: getDateTimeString(3, 14, 0),
    endTime: getDateTimeString(3, 14, 30),
    type: 0 as AppointmentType,
    status: 0 as AppointmentStatus,
    notes: "Prenatal consultation",
    patient: {
      id: 10,
      fullNameEn: "Layla Mansoor Al Rumaithi",
      phoneNumber: "+971500123456",
    },
    provider: { id: 2, fullName: "Dr. Sara Al Ameri" },
    branch: { id: 1, name: "Main Clinic - Dubai" },
  },
];

export const appointmentsData = {
  appointments,
};

// ============================================================
// MULTI-TENANCY MODULE
// ============================================================

const tenants: Tenant[] = [
  {
    id: 1,
    name: "XenonClinic UAE",
    subdomain: "xenonclinic",
    status: 0 as TenantStatus, // Active
    plan: 3 as SubscriptionPlan, // Enterprise
    contactEmail: "admin@xenonclinic.ae",
    contactPhone: "+971800XENON",
    maxUsers: 100,
    maxCompanies: 5,
    storageQuotaGB: 500,
    usedStorageGB: 125,
    subscriptionStart: yearsAgo(2),
    subscriptionEnd: daysFromNow(365),
    settings: {
      logoUrl: "/logos/xenonclinic.png",
      primaryColor: "#2563eb",
      timezone: "Asia/Dubai",
      dateFormat: "DD/MM/YYYY",
      currency: "AED",
      language: "en",
      features: [
        "audiology",
        "dental",
        "pharmacy",
        "laboratory",
        "radiology",
        "hr",
        "payroll",
      ],
    },
    createdAt: yearsAgo(2),
  },
  {
    id: 2,
    name: "MediCare Group",
    subdomain: "medicare",
    status: 0 as TenantStatus,
    plan: 2 as SubscriptionPlan, // Professional
    contactEmail: "admin@medicaregroup.ae",
    contactPhone: "+971800MEDI",
    maxUsers: 50,
    maxCompanies: 3,
    storageQuotaGB: 200,
    usedStorageGB: 45,
    subscriptionStart: yearsAgo(1),
    subscriptionEnd: daysFromNow(180),
    settings: {
      primaryColor: "#059669",
      timezone: "Asia/Dubai",
      dateFormat: "DD/MM/YYYY",
      currency: "AED",
      language: "ar",
      features: ["general", "pharmacy", "laboratory"],
    },
    createdAt: yearsAgo(1),
  },
  {
    id: 3,
    name: "HealthFirst Clinics",
    subdomain: "healthfirst",
    status: 2 as TenantStatus, // PendingActivation
    plan: 0 as SubscriptionPlan, // Trial
    contactEmail: "info@healthfirst.ae",
    contactPhone: "+971501234567",
    maxUsers: 10,
    maxCompanies: 1,
    storageQuotaGB: 10,
    usedStorageGB: 0.5,
    subscriptionStart: daysAgo(7),
    subscriptionEnd: daysFromNow(23),
    createdAt: daysAgo(7),
  },
];

const companies: Company[] = [
  {
    id: 1,
    tenantId: 1,
    name: "XenonClinic Medical Center",
    nameAr: "مركز زينون كلينيك الطبي",
    legalName: "XenonClinic Medical Services LLC",
    registrationNumber: "DXB-12345-2020",
    taxNumber: "100123456789012",
    email: "info@xenonclinic.ae",
    phone: "+97142345678",
    address: "Building 45, Healthcare City",
    city: "Dubai",
    country: "UAE",
    logoUrl: "/logos/xenonclinic.png",
    isActive: true,
    createdAt: yearsAgo(2),
  },
  {
    id: 2,
    tenantId: 1,
    name: "XenonClinic Dental Care",
    nameAr: "زينون كلينيك لطب الأسنان",
    legalName: "XenonClinic Dental LLC",
    registrationNumber: "DXB-12346-2021",
    taxNumber: "100123456789013",
    email: "dental@xenonclinic.ae",
    phone: "+97142345679",
    address: "Tower B, Healthcare City",
    city: "Dubai",
    country: "UAE",
    isActive: true,
    createdAt: yearsAgo(1),
  },
  {
    id: 3,
    tenantId: 2,
    name: "MediCare Family Clinic",
    nameAr: "عيادة ميديكير للعائلة",
    legalName: "MediCare Group LLC",
    registrationNumber: "AUH-54321-2022",
    taxNumber: "100987654321012",
    email: "info@medicaregroup.ae",
    phone: "+97126789012",
    address: "Medical District, Building 10",
    city: "Abu Dhabi",
    country: "UAE",
    isActive: true,
    createdAt: yearsAgo(1),
  },
];

const branches: Branch[] = [
  {
    id: 1,
    companyId: 1,
    companyName: "XenonClinic Medical Center",
    name: "Main Clinic - Dubai",
    nameAr: "العيادة الرئيسية - دبي",
    code: "DXB-MAIN",
    address: "Building 45, Healthcare City",
    city: "Dubai",
    phone: "+97142345678",
    email: "dubai.main@xenonclinic.ae",
    manager: "Dr. Khalid Mohammed",
    workingHours: {
      monday: {
        isOpen: true,
        openTime: "08:00",
        closeTime: "20:00",
        breakStart: "13:00",
        breakEnd: "14:00",
      },
      tuesday: {
        isOpen: true,
        openTime: "08:00",
        closeTime: "20:00",
        breakStart: "13:00",
        breakEnd: "14:00",
      },
      wednesday: {
        isOpen: true,
        openTime: "08:00",
        closeTime: "20:00",
        breakStart: "13:00",
        breakEnd: "14:00",
      },
      thursday: {
        isOpen: true,
        openTime: "08:00",
        closeTime: "20:00",
        breakStart: "13:00",
        breakEnd: "14:00",
      },
      friday: { isOpen: true, openTime: "14:00", closeTime: "20:00" },
      saturday: { isOpen: true, openTime: "09:00", closeTime: "18:00" },
      sunday: { isOpen: true, openTime: "09:00", closeTime: "18:00" },
    },
    isMainBranch: true,
    isActive: true,
    latitude: 25.2285,
    longitude: 55.3273,
    createdAt: yearsAgo(2),
  },
  {
    id: 2,
    companyId: 1,
    companyName: "XenonClinic Medical Center",
    name: "Branch - Abu Dhabi",
    nameAr: "الفرع - أبوظبي",
    code: "AUH-001",
    address: "Al Reem Island, Tower 5",
    city: "Abu Dhabi",
    phone: "+97126789012",
    email: "abudhabi@xenonclinic.ae",
    manager: "Dr. Ahmed Al Hashemi",
    workingHours: {
      monday: { isOpen: true, openTime: "08:00", closeTime: "18:00" },
      tuesday: { isOpen: true, openTime: "08:00", closeTime: "18:00" },
      wednesday: { isOpen: true, openTime: "08:00", closeTime: "18:00" },
      thursday: { isOpen: true, openTime: "08:00", closeTime: "18:00" },
      friday: { isOpen: false },
      saturday: { isOpen: true, openTime: "09:00", closeTime: "14:00" },
      sunday: { isOpen: true, openTime: "09:00", closeTime: "18:00" },
    },
    isMainBranch: false,
    isActive: true,
    latitude: 24.4949,
    longitude: 54.4031,
    createdAt: yearsAgo(1),
  },
  {
    id: 3,
    companyId: 2,
    companyName: "XenonClinic Dental Care",
    name: "Dental Center - Dubai",
    nameAr: "مركز الأسنان - دبي",
    code: "DXB-DENT",
    address: "Tower B, Healthcare City",
    city: "Dubai",
    phone: "+97142345679",
    email: "dental@xenonclinic.ae",
    manager: "Dr. Maha Al Blooshi",
    isMainBranch: true,
    isActive: true,
    createdAt: yearsAgo(1),
  },
];

const tenantUsers: TenantUser[] = [
  {
    id: 1,
    tenantId: 1,
    companyId: 1,
    branchId: 1,
    username: "admin",
    email: "admin@xenonclinic.ae",
    fullName: "System Administrator",
    role: "Admin",
    permissions: ["*"],
    isActive: true,
    lastLogin: daysAgo(0),
    createdAt: yearsAgo(2),
  },
  {
    id: 2,
    tenantId: 1,
    companyId: 1,
    branchId: 1,
    username: "dr.khalid",
    email: "khalid@xenonclinic.ae",
    fullName: "Dr. Khalid Mohammed",
    role: "Doctor",
    permissions: [
      "patients.view",
      "patients.edit",
      "appointments.manage",
      "clinical.full",
    ],
    isActive: true,
    lastLogin: daysAgo(0),
    createdAt: yearsAgo(2),
  },
  {
    id: 3,
    tenantId: 1,
    companyId: 1,
    branchId: 1,
    username: "dr.sara",
    email: "sara@xenonclinic.ae",
    fullName: "Dr. Sara Al Ameri",
    role: "Doctor",
    permissions: [
      "patients.view",
      "patients.edit",
      "appointments.manage",
      "clinical.full",
    ],
    isActive: true,
    lastLogin: daysAgo(1),
    createdAt: yearsAgo(1),
  },
  {
    id: 4,
    tenantId: 1,
    companyId: 1,
    branchId: 2,
    username: "dr.ahmed",
    email: "ahmed@xenonclinic.ae",
    fullName: "Dr. Ahmed Al Hashemi",
    role: "Doctor",
    permissions: [
      "patients.view",
      "patients.edit",
      "appointments.manage",
      "clinical.full",
    ],
    isActive: true,
    lastLogin: daysAgo(0),
    createdAt: yearsAgo(1),
  },
  {
    id: 5,
    tenantId: 1,
    companyId: 1,
    branchId: 1,
    username: "reception1",
    email: "reception@xenonclinic.ae",
    fullName: "Fatima Receptionist",
    role: "Receptionist",
    permissions: ["patients.view", "appointments.manage", "billing.view"],
    isActive: true,
    lastLogin: daysAgo(0),
    createdAt: monthsAgo(6),
  },
  {
    id: 6,
    tenantId: 1,
    companyId: 1,
    branchId: 1,
    username: "nurse.aisha",
    email: "aisha@xenonclinic.ae",
    fullName: "Nurse Aisha Mohammed",
    role: "Nurse",
    permissions: ["patients.view", "vitals.manage", "appointments.view"],
    isActive: true,
    lastLogin: daysAgo(0),
    createdAt: monthsAgo(8),
  },
];

const subscriptions: Subscription[] = [
  {
    id: 1,
    tenantId: 1,
    plan: 3 as SubscriptionPlan,
    status: "active",
    startDate: yearsAgo(2),
    endDate: daysFromNow(365),
    autoRenew: true,
    billingCycle: "annually",
    amount: 120000,
    currency: "AED",
    nextBillingDate: daysFromNow(365),
    paymentMethod: "Bank Transfer",
  },
  {
    id: 2,
    tenantId: 2,
    plan: 2 as SubscriptionPlan,
    status: "active",
    startDate: yearsAgo(1),
    endDate: daysFromNow(180),
    autoRenew: true,
    billingCycle: "quarterly",
    amount: 15000,
    currency: "AED",
    nextBillingDate: daysFromNow(90),
    paymentMethod: "Credit Card",
  },
  {
    id: 3,
    tenantId: 3,
    plan: 0 as SubscriptionPlan,
    status: "pending",
    startDate: daysAgo(7),
    endDate: daysFromNow(23),
    autoRenew: false,
    billingCycle: "monthly",
    amount: 0,
    currency: "AED",
  },
];

export const multiTenancyData = {
  tenants,
  companies,
  branches,
  users: tenantUsers,
  subscriptions,
};

// ============================================================
// USERS/AUTH MODULE
// ============================================================

const users: User[] = [
  {
    id: "1",
    username: "admin",
    email: "admin@xenonclinic.ae",
    fullName: "System Administrator",
    roles: ["Admin", "SuperUser"],
  },
  {
    id: "2",
    username: "dr.khalid",
    email: "khalid@xenonclinic.ae",
    fullName: "Dr. Khalid Mohammed",
    roles: ["Doctor", "BranchManager"],
  },
  {
    id: "3",
    username: "dr.sara",
    email: "sara@xenonclinic.ae",
    fullName: "Dr. Sara Al Ameri",
    roles: ["Doctor"],
  },
  {
    id: "4",
    username: "dr.ahmed",
    email: "ahmed@xenonclinic.ae",
    fullName: "Dr. Ahmed Al Hashemi",
    roles: ["Doctor", "BranchManager"],
  },
  {
    id: "5",
    username: "hr.manager",
    email: "hr@xenonclinic.ae",
    fullName: "Mohammed HR Manager",
    roles: ["HRManager"],
  },
  {
    id: "6",
    username: "finance.manager",
    email: "finance@xenonclinic.ae",
    fullName: "Layla Finance Manager",
    roles: ["FinanceManager"],
  },
  {
    id: "7",
    username: "lab.tech",
    email: "lab@xenonclinic.ae",
    fullName: "Omar Lab Technician",
    roles: ["LabTechnician"],
  },
  {
    id: "8",
    username: "pharmacist",
    email: "pharmacy@xenonclinic.ae",
    fullName: "Huda Pharmacist",
    roles: ["Pharmacist"],
  },
];

export const usersData = {
  users,
};

// ============================================================
// SECURITY MODULE
// ============================================================

const auditLogs: AuditLog[] = [
  {
    id: 1,
    timestamp: getDateTimeString(0, 8, 15),
    userId: 1,
    username: "admin",
    userRole: "Admin",
    action: 4 as AuditActionType, // Login
    module: "Authentication",
    entityType: "Session",
    description: "User logged in successfully",
    ipAddress: "192.168.1.100",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
    success: true,
  },
  {
    id: 2,
    timestamp: getDateTimeString(0, 9, 30),
    userId: 2,
    username: "dr.khalid",
    userRole: "Doctor",
    action: 1 as AuditActionType, // Read
    module: "Patients",
    entityType: "Patient",
    entityId: 1,
    description: "Viewed patient record: Ahmed Hassan Al Maktoum",
    ipAddress: "192.168.1.105",
    success: true,
  },
  {
    id: 3,
    timestamp: getDateTimeString(0, 10, 15),
    userId: 2,
    username: "dr.khalid",
    userRole: "Doctor",
    action: 2 as AuditActionType, // Update
    module: "Patients",
    entityType: "Patient",
    entityId: 1,
    description: "Updated patient diagnosis",
    ipAddress: "192.168.1.105",
    oldValue: '{"diagnosis": "Pending"}',
    newValue: '{"diagnosis": "Tension-type headache"}',
    success: true,
  },
  {
    id: 4,
    timestamp: getDateTimeString(-1, 14, 0),
    userId: 5,
    username: "reception1",
    userRole: "Receptionist",
    action: 0 as AuditActionType, // Create
    module: "Appointments",
    entityType: "Appointment",
    entityId: 15,
    description: "Created new appointment for patient",
    ipAddress: "192.168.1.110",
    success: true,
  },
  {
    id: 5,
    timestamp: getDateTimeString(-1, 16, 30),
    userId: 0,
    username: "unknown",
    userRole: "Unknown",
    action: 10 as AuditActionType, // Failed
    module: "Authentication",
    entityType: "Session",
    description: "Failed login attempt",
    ipAddress: "203.45.67.89",
    success: false,
    errorMessage: "Invalid credentials",
  },
];

const permissions: Permission[] = [
  {
    id: 1,
    name: "patients.view",
    module: "Patients",
    description: "View patient records",
    granted: true,
    grantedAt: yearsAgo(2),
    grantedBy: "System",
  },
  {
    id: 2,
    name: "patients.create",
    module: "Patients",
    description: "Create new patients",
    granted: true,
    grantedAt: yearsAgo(2),
    grantedBy: "System",
  },
  {
    id: 3,
    name: "patients.edit",
    module: "Patients",
    description: "Edit patient records",
    granted: true,
    grantedAt: yearsAgo(2),
    grantedBy: "System",
  },
  {
    id: 4,
    name: "patients.delete",
    module: "Patients",
    description: "Delete patient records",
    granted: false,
  },
  {
    id: 5,
    name: "appointments.view",
    module: "Appointments",
    description: "View appointments",
    granted: true,
    grantedAt: yearsAgo(2),
    grantedBy: "System",
  },
  {
    id: 6,
    name: "appointments.manage",
    module: "Appointments",
    description: "Create and edit appointments",
    granted: true,
    grantedAt: yearsAgo(2),
    grantedBy: "System",
  },
  {
    id: 7,
    name: "clinical.full",
    module: "Clinical",
    description: "Full clinical access",
    granted: true,
    grantedAt: yearsAgo(2),
    grantedBy: "System",
  },
  {
    id: 8,
    name: "billing.view",
    module: "Billing",
    description: "View billing information",
    granted: true,
    grantedAt: monthsAgo(6),
    grantedBy: "admin",
  },
  {
    id: 9,
    name: "billing.manage",
    module: "Billing",
    description: "Manage billing and payments",
    granted: false,
  },
  {
    id: 10,
    name: "reports.view",
    module: "Reports",
    description: "View reports",
    granted: true,
    grantedAt: yearsAgo(1),
    grantedBy: "admin",
  },
  {
    id: 11,
    name: "reports.export",
    module: "Reports",
    description: "Export reports",
    granted: true,
    grantedAt: yearsAgo(1),
    grantedBy: "admin",
  },
  {
    id: 12,
    name: "admin.users",
    module: "Admin",
    description: "Manage users",
    granted: false,
  },
  {
    id: 13,
    name: "admin.settings",
    module: "Admin",
    description: "System settings",
    granted: false,
  },
  {
    id: 14,
    name: "hr.view",
    module: "HR",
    description: "View HR records",
    granted: true,
    grantedAt: monthsAgo(3),
    grantedBy: "admin",
  },
  {
    id: 15,
    name: "hr.manage",
    module: "HR",
    description: "Manage HR records",
    granted: false,
  },
];

const userAccessReviews: UserAccessReview[] = [
  {
    id: 1,
    userId: 2,
    username: "dr.khalid",
    fullName: "Dr. Khalid Mohammed",
    email: "khalid@xenonclinic.ae",
    role: "Doctor",
    department: "General Medicine",
    permissions: permissions.filter((p) =>
      [1, 2, 3, 5, 6, 7, 10, 11].includes(p.id),
    ),
    lastLogin: daysAgo(0),
    lastPasswordChange: monthsAgo(2),
    accountStatus: "active",
    mfaEnabled: true,
    reviewStatus: "approved",
    reviewedBy: "admin",
    reviewedAt: monthsAgo(1),
    reviewNotes: "Access appropriate for role",
  },
  {
    id: 2,
    userId: 5,
    username: "reception1",
    fullName: "Fatima Receptionist",
    email: "reception@xenonclinic.ae",
    role: "Receptionist",
    department: "Front Desk",
    permissions: permissions.filter((p) => [1, 5, 6, 8].includes(p.id)),
    lastLogin: daysAgo(0),
    lastPasswordChange: monthsAgo(1),
    accountStatus: "active",
    mfaEnabled: false,
    reviewStatus: "pending",
    reviewNotes: "Quarterly access review due",
  },
];

const passwordPolicies: PasswordPolicy[] = [
  {
    id: 1,
    name: "Standard Policy",
    minLength: 8,
    requireUppercase: true,
    requireLowercase: true,
    requireNumbers: true,
    requireSpecialChars: true,
    preventReuse: 5,
    maxAge: 90,
    lockoutThreshold: 5,
    lockoutDuration: 30,
    mfaRequired: false,
    sessionTimeout: 480,
    isDefault: true,
    isActive: true,
    createdAt: yearsAgo(2),
  },
  {
    id: 2,
    name: "High Security Policy",
    minLength: 12,
    requireUppercase: true,
    requireLowercase: true,
    requireNumbers: true,
    requireSpecialChars: true,
    preventReuse: 10,
    maxAge: 60,
    lockoutThreshold: 3,
    lockoutDuration: 60,
    mfaRequired: true,
    sessionTimeout: 240,
    isDefault: false,
    isActive: true,
    createdAt: yearsAgo(1),
  },
];

const securityIncidents: SecurityIncident[] = [
  {
    id: 1,
    incidentNumber: "INC-2024-001",
    title: "Multiple Failed Login Attempts",
    description:
      "Detected 15 failed login attempts from external IP address targeting multiple accounts",
    severity: 1 as SecurityAlertSeverity, // Medium
    status: "resolved",
    type: "Brute Force Attempt",
    affectedUsers: ["dr.khalid", "dr.sara", "admin"],
    detectedAt: weeksAgo(2),
    reportedBy: "Security Monitoring System",
    assignedTo: "admin",
    resolvedAt: weeksAgo(2),
    resolution:
      "IP address blocked, affected users notified to change passwords",
    preventiveMeasures: "Implemented rate limiting on login endpoint",
    createdAt: weeksAgo(2),
  },
  {
    id: 2,
    incidentNumber: "INC-2024-002",
    title: "Unauthorized Access Attempt",
    description:
      "User attempted to access restricted patient records without proper authorization",
    severity: 2 as SecurityAlertSeverity, // High
    status: "investigating",
    type: "Unauthorized Access",
    affectedUsers: ["temp.staff"],
    affectedSystems: ["Patient Records Module"],
    detectedAt: daysAgo(3),
    reportedBy: "Audit System",
    assignedTo: "hr.manager",
    createdAt: daysAgo(3),
  },
];

const complianceReports: ComplianceReport[] = [
  {
    id: 1,
    reportName: "HIPAA Compliance Assessment Q4 2024",
    reportType: "HIPAA",
    period: "Q4 2024",
    status: "approved",
    complianceScore: 94,
    findings: [
      {
        id: 1,
        category: "Access Control",
        requirement: "Unique user identification",
        status: "compliant",
        priority: "high",
      },
      {
        id: 2,
        category: "Access Control",
        requirement: "Emergency access procedures",
        status: "compliant",
        priority: "high",
      },
      {
        id: 3,
        category: "Audit Controls",
        requirement: "Audit logging enabled",
        status: "compliant",
        priority: "high",
      },
      {
        id: 4,
        category: "Integrity",
        requirement: "Data backup procedures",
        status: "partial",
        remediation: "Increase backup frequency",
        dueDate: daysFromNow(30),
        priority: "medium",
      },
      {
        id: 5,
        category: "Transmission Security",
        requirement: "Encryption in transit",
        status: "compliant",
        priority: "critical",
      },
    ],
    generatedAt: monthsAgo(1),
    generatedBy: "Compliance Officer",
    approvedBy: "admin",
    approvedAt: weeksAgo(3),
  },
];

const loginAttempts: LoginAttempt[] = [
  {
    id: 1,
    username: "admin",
    ipAddress: "192.168.1.100",
    timestamp: getDateTimeString(0, 8, 15),
    success: true,
    userAgent: "Chrome/120.0",
  },
  {
    id: 2,
    username: "dr.khalid",
    ipAddress: "192.168.1.105",
    timestamp: getDateTimeString(0, 8, 30),
    success: true,
    userAgent: "Safari/17.0",
  },
  {
    id: 3,
    username: "dr.sara",
    ipAddress: "192.168.1.106",
    timestamp: getDateTimeString(0, 9, 0),
    success: true,
    userAgent: "Firefox/121.0",
  },
  {
    id: 4,
    username: "unknown",
    ipAddress: "203.45.67.89",
    timestamp: getDateTimeString(-1, 16, 30),
    success: false,
    failureReason: "Invalid username",
    userAgent: "curl/7.88",
  },
  {
    id: 5,
    username: "admin",
    ipAddress: "203.45.67.89",
    timestamp: getDateTimeString(-1, 16, 31),
    success: false,
    failureReason: "Invalid password",
    userAgent: "curl/7.88",
  },
];

const sessions: Session[] = [
  {
    id: "sess-001",
    userId: 1,
    username: "admin",
    ipAddress: "192.168.1.100",
    userAgent: "Chrome/120.0",
    startedAt: getDateTimeString(0, 8, 15),
    lastActivity: getDateTimeString(0, 11, 30),
    expiresAt: getDateTimeString(0, 16, 15),
    isActive: true,
  },
  {
    id: "sess-002",
    userId: 2,
    username: "dr.khalid",
    ipAddress: "192.168.1.105",
    userAgent: "Safari/17.0",
    startedAt: getDateTimeString(0, 8, 30),
    lastActivity: getDateTimeString(0, 11, 45),
    expiresAt: getDateTimeString(0, 16, 30),
    isActive: true,
  },
  {
    id: "sess-003",
    userId: 3,
    username: "dr.sara",
    ipAddress: "192.168.1.106",
    userAgent: "Firefox/121.0",
    startedAt: getDateTimeString(0, 9, 0),
    lastActivity: getDateTimeString(0, 10, 30),
    expiresAt: getDateTimeString(0, 17, 0),
    isActive: true,
  },
  {
    id: "sess-004",
    userId: 5,
    username: "reception1",
    ipAddress: "192.168.1.110",
    userAgent: "Edge/120.0",
    startedAt: getDateTimeString(-1, 8, 0),
    lastActivity: getDateTimeString(-1, 17, 0),
    expiresAt: getDateTimeString(-1, 16, 0),
    isActive: false,
  },
];

export const securityData = {
  auditLogs,
  permissions,
  userAccessReviews,
  passwordPolicies,
  securityIncidents,
  complianceReports,
  loginAttempts,
  sessions,
};

// ============================================================
// PAYROLL MODULE (DETAILED)
// ============================================================

const salaryStructures: SalaryStructure[] = [
  {
    id: 1,
    name: "Doctor - Senior",
    basicSalary: 35000,
    housingAllowance: 8000,
    transportAllowance: 2500,
    otherAllowances: 3000,
    effectiveDate: yearsAgo(1),
    isActive: true,
    description: "Salary structure for senior doctors with 5+ years experience",
    employeeCount: 3,
    createdAt: yearsAgo(1),
  },
  {
    id: 2,
    name: "Doctor - Junior",
    basicSalary: 25000,
    housingAllowance: 6000,
    transportAllowance: 2000,
    otherAllowances: 2000,
    effectiveDate: yearsAgo(1),
    isActive: true,
    description:
      "Salary structure for junior doctors with less than 5 years experience",
    employeeCount: 5,
    createdAt: yearsAgo(1),
  },
  {
    id: 3,
    name: "Nurse",
    basicSalary: 12000,
    housingAllowance: 4000,
    transportAllowance: 1500,
    otherAllowances: 1000,
    effectiveDate: yearsAgo(1),
    isActive: true,
    description: "Standard nurse salary structure",
    employeeCount: 10,
    createdAt: yearsAgo(1),
  },
  {
    id: 4,
    name: "Administrative Staff",
    basicSalary: 8000,
    housingAllowance: 3000,
    transportAllowance: 1000,
    otherAllowances: 500,
    effectiveDate: yearsAgo(1),
    isActive: true,
    description: "Salary structure for administrative and reception staff",
    employeeCount: 8,
    createdAt: yearsAgo(1),
  },
  {
    id: 5,
    name: "Technician",
    basicSalary: 10000,
    housingAllowance: 3500,
    transportAllowance: 1500,
    otherAllowances: 1000,
    effectiveDate: yearsAgo(1),
    isActive: true,
    description: "Salary structure for lab and radiology technicians",
    employeeCount: 6,
    createdAt: yearsAgo(1),
  },
  {
    id: 6,
    name: "Manager",
    basicSalary: 28000,
    housingAllowance: 7000,
    transportAllowance: 2500,
    otherAllowances: 3500,
    effectiveDate: yearsAgo(1),
    isActive: true,
    description: "Salary structure for department managers",
    employeeCount: 4,
    createdAt: yearsAgo(1),
  },
];

const payrollRecords: PayrollRecord[] = [
  {
    id: 1,
    employeeId: 1,
    employeeName: "Dr. Khalid Mohammed",
    employeeNumber: "EMP-001",
    department: "General Medicine",
    period: "December 2024",
    basicSalary: 35000,
    allowances: [
      { id: 1, name: "Housing", amount: 8000 },
      { id: 2, name: "Transport", amount: 2500 },
      { id: 3, name: "Medical", amount: 1500 },
      { id: 4, name: "Phone", amount: 500 },
    ],
    deductions: [
      { id: 1, name: "Social Insurance", amount: 875 },
      { id: 2, name: "Professional License", amount: 200 },
    ],
    totalAllowances: 12500,
    totalDeductions: 1075,
    grossSalary: 47500,
    netSalary: 46425,
    status: 3 as PayrollStatus, // Paid
    processedDate: daysAgo(5),
    approvedDate: daysAgo(4),
    approvedBy: "Finance Manager",
    paidDate: daysAgo(1),
    paidBy: "Payroll System",
    paymentMethod: "Bank Transfer",
    createdAt: daysAgo(10),
  },
  {
    id: 2,
    employeeId: 2,
    employeeName: "Dr. Sara Al Ameri",
    employeeNumber: "EMP-002",
    department: "Pediatrics",
    period: "December 2024",
    basicSalary: 30000,
    allowances: [
      { id: 1, name: "Housing", amount: 7000 },
      { id: 2, name: "Transport", amount: 2000 },
      { id: 3, name: "Medical", amount: 1200 },
    ],
    deductions: [{ id: 1, name: "Social Insurance", amount: 750 }],
    totalAllowances: 10200,
    totalDeductions: 750,
    grossSalary: 40200,
    netSalary: 39450,
    status: 2 as PayrollStatus, // Approved
    processedDate: daysAgo(5),
    approvedDate: daysAgo(3),
    approvedBy: "Finance Manager",
    createdAt: daysAgo(10),
  },
  {
    id: 3,
    employeeId: 3,
    employeeName: "Nurse Aisha Mohammed",
    employeeNumber: "EMP-003",
    department: "Nursing",
    period: "December 2024",
    basicSalary: 12000,
    allowances: [
      { id: 1, name: "Housing", amount: 4000 },
      { id: 2, name: "Transport", amount: 1500 },
      { id: 3, name: "Overtime", amount: 2400 },
    ],
    deductions: [{ id: 1, name: "Social Insurance", amount: 300 }],
    totalAllowances: 7900,
    totalDeductions: 300,
    grossSalary: 19900,
    netSalary: 19600,
    status: 1 as PayrollStatus, // Processed
    processedDate: daysAgo(3),
    createdAt: daysAgo(10),
  },
];

const employees: Employee[] = [
  {
    id: 1,
    employeeNumber: "EMP-001",
    fullName: "Dr. Khalid Mohammed",
    email: "khalid@xenonclinic.ae",
    phoneNumber: "+971501111111",
    role: 0 as EmployeeRole, // Doctor
    department: "General Medicine",
    status: 0 as EmployeeStatus, // Active
    hireDate: yearsAgo(5),
    salary: 47500,
    nationalId: "784-1980-1234567-1",
    dateOfBirth: "1980-05-15",
    address: "Dubai Marina, Tower A",
    emergencyContact: "Fatima Mohammed",
    emergencyPhone: "+971502222222",
    createdAt: yearsAgo(5),
  },
  {
    id: 2,
    employeeNumber: "EMP-002",
    fullName: "Dr. Sara Al Ameri",
    email: "sara@xenonclinic.ae",
    phoneNumber: "+971503333333",
    role: 0 as EmployeeRole,
    department: "Pediatrics",
    status: 0 as EmployeeStatus,
    hireDate: yearsAgo(3),
    salary: 40200,
    nationalId: "784-1988-2345678-2",
    dateOfBirth: "1988-08-22",
    createdAt: yearsAgo(3),
  },
  {
    id: 3,
    employeeNumber: "EMP-003",
    fullName: "Nurse Aisha Mohammed",
    email: "aisha@xenonclinic.ae",
    phoneNumber: "+971504444444",
    role: 1 as EmployeeRole, // Nurse
    department: "Nursing",
    status: 0 as EmployeeStatus,
    hireDate: yearsAgo(2),
    salary: 18500,
    nationalId: "784-1992-3456789-3",
    dateOfBirth: "1992-03-10",
    createdAt: yearsAgo(2),
  },
  {
    id: 4,
    employeeNumber: "EMP-004",
    fullName: "Fatima Al Rashid",
    email: "reception@xenonclinic.ae",
    phoneNumber: "+971505555555",
    role: 2 as EmployeeRole, // Receptionist
    department: "Front Desk",
    status: 0 as EmployeeStatus,
    hireDate: monthsAgo(18),
    salary: 12500,
    createdAt: monthsAgo(18),
  },
  {
    id: 5,
    employeeNumber: "EMP-005",
    fullName: "Omar Lab Technician",
    email: "lab@xenonclinic.ae",
    phoneNumber: "+971506666666",
    role: 3 as EmployeeRole, // Technician
    department: "Laboratory",
    status: 0 as EmployeeStatus,
    hireDate: yearsAgo(1),
    salary: 16000,
    createdAt: yearsAgo(1),
  },
  {
    id: 6,
    employeeNumber: "EMP-006",
    fullName: "Mohammed HR Manager",
    email: "hr@xenonclinic.ae",
    phoneNumber: "+971507777777",
    role: 4 as EmployeeRole, // Administrator
    department: "Human Resources",
    status: 0 as EmployeeStatus,
    hireDate: yearsAgo(4),
    salary: 41000,
    createdAt: yearsAgo(4),
  },
  {
    id: 7,
    employeeNumber: "EMP-007",
    fullName: "Ahmad Al Mansoor",
    email: "ahmad@xenonclinic.ae",
    phoneNumber: "+971508888888",
    role: 1 as EmployeeRole,
    department: "Nursing",
    status: 1 as EmployeeStatus, // OnLeave
    hireDate: yearsAgo(2),
    salary: 18500,
    createdAt: yearsAgo(2),
  },
];

export const payrollData = {
  salaryStructures,
  payrollRecords,
  employees,
};

// ============================================================
// COMBINED EXPORT
// ============================================================

export const allCoreModulesData = {
  patients: patientsData,
  appointments: appointmentsData,
  multiTenancy: multiTenancyData,
  users: usersData,
  security: securityData,
  payroll: payrollData,
};
