/**
 * Specialty Demo Data
 * Comprehensive seed data for all medical specialty modules
 */

// ============================================
// HELPER FUNCTIONS
// ============================================

const getDateString = (daysFromNow: number): string => {
  const date = new Date();
  date.setDate(date.getDate() + daysFromNow);
  return date.toISOString().split("T")[0];
};

// ============================================
// ORTHOPEDICS DEMO DATA
// ============================================

export const orthopedicsData = {
  exams: [
    {
      id: 1,
      patientId: 1,
      patientName: "Ahmed Hassan Al Maktoum",
      examDate: getDateString(-7),
      chiefComplaint: "Right knee pain after sports injury",
      affectedArea: "Right Knee",
      rangeOfMotion: "Flexion 120°, Extension 0°, limited by pain",
      strength: "4/5 quadriceps, 5/5 hamstrings",
      stability: "ACL laxity grade 2, MCL stable",
      specialTests: "Lachman positive, McMurray negative",
      diagnosis: "ACL partial tear, right knee",
      plan: "MRI recommended, physiotherapy referral, consider surgical consult",
      performedBy: "Dr. Khalid Al Mansouri",
      notes: "Patient is active soccer player, eager to return to sports",
    },
    {
      id: 2,
      patientId: 2,
      patientName: "Fatima Khalid Al Nahyan",
      examDate: getDateString(-14),
      chiefComplaint: "Lower back pain radiating to left leg",
      affectedArea: "Lumbar Spine",
      rangeOfMotion: "Limited flexion 60°, extension 10°",
      strength: "4/5 L4-L5 myotomes bilateral",
      stability: "No instability noted",
      specialTests: "SLR positive at 45° left, negative right",
      diagnosis: "L4-L5 disc herniation with radiculopathy",
      plan: "MRI lumbar spine, NSAIDs, PT referral, epidural if no improvement",
      performedBy: "Dr. Khalid Al Mansouri",
    },
    {
      id: 3,
      patientId: 3,
      patientName: "Mohammed Rashid Al Falasi",
      examDate: getDateString(-3),
      chiefComplaint: "Right shoulder pain, difficulty lifting arm",
      affectedArea: "Right Shoulder",
      rangeOfMotion:
        "Abduction 90°, forward flexion 120°, external rotation 30°",
      strength: "3/5 supraspinatus, 4/5 deltoid",
      stability: "Glenohumeral joint stable",
      specialTests: "Neer positive, Hawkins positive, Empty can positive",
      diagnosis: "Rotator cuff tendinopathy with possible partial tear",
      plan: "Ultrasound/MRI, PT for 6 weeks, steroid injection if needed",
      performedBy: "Dr. Sarah Ahmed",
    },
    {
      id: 4,
      patientId: 4,
      patientName: "Sara Omar Al Ketbi",
      examDate: getDateString(-1),
      chiefComplaint: "Bilateral hip pain, worse on walking",
      affectedArea: "Bilateral Hips",
      rangeOfMotion: "Right: IR 15°, ER 30°; Left: IR 20°, ER 35°",
      strength: "4/5 hip flexors bilateral",
      stability: "Stable",
      specialTests: "FABER positive bilateral, FADIR positive bilateral",
      diagnosis: "Bilateral hip osteoarthritis, moderate",
      plan: "X-rays bilateral hips, weight management, PT, consider injections",
      performedBy: "Dr. Khalid Al Mansouri",
    },
    {
      id: 5,
      patientId: 5,
      patientName: "Khalid Ibrahim Al Suwaidi",
      examDate: getDateString(0),
      chiefComplaint: "Left wrist pain after fall",
      affectedArea: "Left Wrist",
      rangeOfMotion: "Flexion 45°, extension 30°, limited by swelling",
      strength: "Unable to assess due to pain",
      stability: "Point tenderness over distal radius",
      specialTests: "Anatomical snuffbox tenderness negative",
      diagnosis: "Suspected distal radius fracture",
      plan: "X-ray left wrist, splint immobilization, follow-up with results",
      performedBy: "Dr. Sarah Ahmed",
      notes: "Fell on outstretched hand yesterday",
    },
  ],
  fractures: [
    {
      id: 1,
      patientId: 5,
      patientName: "Khalid Ibrahim Al Suwaidi",
      fractureDate: getDateString(-1),
      boneAffected: "Distal Radius",
      fractureType: "Colles Fracture",
      location: "Left wrist, distal radius metaphysis",
      displacement: "Dorsal angulation 15°, 3mm shortening",
      treatment: "Closed reduction and casting",
      castType: "Short arm cast",
      expectedHealingTime: 6,
      followUpDate: getDateString(14),
      status: 0, // Active
      treatedBy: "Dr. Khalid Al Mansouri",
      notes: "Good reduction achieved, patient tolerating cast well",
    },
    {
      id: 2,
      patientId: 6,
      patientName: "Mariam Abdullah Al Mansouri",
      fractureDate: getDateString(-28),
      boneAffected: "Fibula",
      fractureType: "Lateral Malleolus Fracture",
      location: "Right ankle",
      displacement: "Non-displaced",
      treatment: "Below-knee walking boot",
      castType: "CAM boot",
      expectedHealingTime: 6,
      followUpDate: getDateString(7),
      status: 1, // Healing
      treatedBy: "Dr. Sarah Ahmed",
      notes: "Week 4 X-ray shows good callus formation",
    },
    {
      id: 3,
      patientId: 7,
      patientName: "Hassan Ali Al Shamsi",
      fractureDate: getDateString(-56),
      boneAffected: "Tibia",
      fractureType: "Tibial Shaft Fracture",
      location: "Right mid-tibia",
      displacement: "Initially displaced, surgically fixed",
      treatment: "ORIF with intramedullary nail",
      expectedHealingTime: 12,
      followUpDate: getDateString(28),
      status: 1, // Healing
      treatedBy: "Dr. Khalid Al Mansouri",
      notes: "8 weeks post-op, partial weight bearing initiated",
    },
    {
      id: 4,
      patientId: 8,
      patientName: "Layla Youssef Al Zaabi",
      fractureDate: getDateString(-90),
      boneAffected: "Clavicle",
      fractureType: "Midshaft Clavicle Fracture",
      location: "Left clavicle",
      displacement: "Non-displaced",
      treatment: "Sling immobilization",
      expectedHealingTime: 8,
      status: 2, // Healed
      treatedBy: "Dr. Sarah Ahmed",
      notes: "Fully healed, full ROM restored",
    },
  ],
  surgeries: [
    {
      id: 1,
      patientId: 7,
      patientName: "Hassan Ali Al Shamsi",
      surgeryDate: getDateString(-56),
      procedure: "Intramedullary Nailing - Tibia",
      indication: "Displaced tibial shaft fracture",
      implants:
        "Titanium IM nail 11mm x 340mm, 2 proximal screws, 2 distal screws",
      surgeon: "Dr. Khalid Al Mansouri",
      assistant: "Dr. Sarah Ahmed",
      anesthesia: "Spinal anesthesia",
      duration: 90,
      postOpInstructions:
        "Non-weight bearing 6 weeks, DVT prophylaxis, PT at week 2",
      outcome: "Uncomplicated, good alignment achieved",
      notes: "Intraoperative fluoroscopy confirmed reduction",
    },
    {
      id: 2,
      patientId: 1,
      patientName: "Ahmed Hassan Al Maktoum",
      surgeryDate: getDateString(14),
      procedure: "ACL Reconstruction",
      indication: "ACL complete tear with instability",
      implants: "Hamstring autograft, bioabsorbable interference screws",
      surgeon: "Dr. Khalid Al Mansouri",
      anesthesia: "General anesthesia",
      duration: 120,
      postOpInstructions:
        "Brace locked in extension, crutches 4 weeks, PT protocol",
      notes: "Surgery scheduled - patient counseled on rehab expectations",
    },
    {
      id: 3,
      patientId: 3,
      patientName: "Mohammed Rashid Al Falasi",
      surgeryDate: getDateString(-180),
      procedure: "Total Knee Replacement",
      indication: "Severe osteoarthritis right knee",
      implants: "Cemented TKR, posterior stabilized design",
      surgeon: "Dr. Khalid Al Mansouri",
      assistant: "Dr. Sarah Ahmed",
      anesthesia: "Spinal with sedation",
      duration: 150,
      postOpInstructions:
        "Weight bearing as tolerated, PT daily, DVT prophylaxis 4 weeks",
      outcome: "Excellent, ROM 0-120° at 6 months",
      notes: "6-month follow-up - patient very satisfied with outcome",
    },
  ],
};

// ============================================
// ONCOLOGY DEMO DATA
// ============================================

export const oncologyData = {
  diagnoses: [
    {
      id: 1,
      patientId: 1,
      patientName: "Ahmed Hassan Al Maktoum",
      diagnosisDate: getDateString(-60),
      cancerType: "lung",
      stage: "stage_2",
      grade: "g2",
      primarySite: "Right upper lobe",
      metastasis: false,
      histology: "Adenocarcinoma",
      diagnosedBy: "Dr. Nadia Al Farsi",
      tnmStaging: { t: "T2a", n: "N1", m: "M0" },
      biomarkers: "EGFR negative, ALK negative, PD-L1 60%",
      notes: "Incidental finding on chest CT, confirmed by bronchoscopy biopsy",
    },
    {
      id: 2,
      patientId: 2,
      patientName: "Fatima Khalid Al Nahyan",
      diagnosisDate: getDateString(-90),
      cancerType: "breast",
      stage: "stage_1",
      grade: "g1",
      primarySite: "Left breast, upper outer quadrant",
      metastasis: false,
      histology: "Invasive ductal carcinoma",
      diagnosedBy: "Dr. Nadia Al Farsi",
      tnmStaging: { t: "T1c", n: "N0", m: "M0" },
      biomarkers: "ER+, PR+, HER2-, Ki67 15%",
      notes: "Detected on screening mammogram, sentinel node biopsy negative",
    },
    {
      id: 3,
      patientId: 3,
      patientName: "Mohammed Rashid Al Falasi",
      diagnosisDate: getDateString(-120),
      cancerType: "colorectal",
      stage: "stage_3",
      grade: "g2",
      primarySite: "Sigmoid colon",
      metastasis: false,
      metastaticSites: [],
      histology: "Adenocarcinoma",
      diagnosedBy: "Dr. Ahmad Malik",
      tnmStaging: { t: "T3", n: "N1", m: "M0" },
      biomarkers: "MSI-H, KRAS wild type",
      notes:
        "Presented with rectal bleeding, colonoscopy with biopsy confirmed",
    },
    {
      id: 4,
      patientId: 4,
      patientName: "Sara Omar Al Ketbi",
      diagnosisDate: getDateString(-30),
      cancerType: "thyroid",
      stage: "stage_1",
      grade: "g1",
      primarySite: "Right thyroid lobe",
      metastasis: false,
      histology: "Papillary thyroid carcinoma",
      diagnosedBy: "Dr. Nadia Al Farsi",
      tnmStaging: { t: "T1b", n: "N0", m: "M0" },
      biomarkers: "Thyroglobulin elevated",
      notes: "Incidental thyroid nodule, FNA confirmed PTC",
    },
    {
      id: 5,
      patientId: 5,
      patientName: "Khalid Ibrahim Al Suwaidi",
      diagnosisDate: getDateString(-180),
      cancerType: "prostate",
      stage: "stage_2",
      grade: "g2",
      primarySite: "Prostate, bilateral involvement",
      metastasis: false,
      histology: "Adenocarcinoma, Gleason 3+4=7",
      diagnosedBy: "Dr. Ahmad Malik",
      tnmStaging: { t: "T2c", n: "N0", m: "M0" },
      biomarkers: "PSA 8.5 ng/mL",
      notes: "Elevated PSA on screening, MRI-guided biopsy confirmed",
    },
  ],
  chemotherapy: [
    {
      id: 1,
      patientId: 1,
      patientName: "Ahmed Hassan Al Maktoum",
      diagnosisId: 1,
      protocolName: "Cisplatin-Pemetrexed",
      drugs: [
        { drugName: "Cisplatin", dosage: 75, unit: "mg/m2", route: "IV" },
        { drugName: "Pemetrexed", dosage: 500, unit: "mg/m2", route: "IV" },
      ],
      schedule: "Day 1 every 21 days",
      cycles: 4,
      completedCycles: 2,
      startDate: getDateString(-45),
      expectedEndDate: getDateString(18),
      status: "active",
      prescribedBy: "Dr. Nadia Al Farsi",
      notes: "Tolerating well, mild nausea managed with antiemetics",
    },
    {
      id: 2,
      patientId: 3,
      patientName: "Mohammed Rashid Al Falasi",
      diagnosisId: 3,
      protocolName: "FOLFOX6",
      drugs: [
        { drugName: "Oxaliplatin", dosage: 85, unit: "mg/m2", route: "IV" },
        { drugName: "Leucovorin", dosage: 400, unit: "mg/m2", route: "IV" },
        {
          drugName: "5-Fluorouracil",
          dosage: 2400,
          unit: "mg/m2",
          route: "IV infusion",
        },
      ],
      schedule: "Every 2 weeks",
      cycles: 12,
      completedCycles: 8,
      startDate: getDateString(-120),
      expectedEndDate: getDateString(8),
      status: "active",
      prescribedBy: "Dr. Ahmad Malik",
      notes: "Grade 1 peripheral neuropathy - monitoring closely",
    },
  ],
  tumorMarkers: [
    {
      id: 1,
      patientId: 1,
      patientName: "Ahmed Hassan Al Maktoum",
      markerType: "cea",
      value: 3.2,
      unit: "ng/mL",
      referenceRange: "<5.0",
      testDate: getDateString(-7),
      trend: "stable",
      previousValue: 3.5,
      orderedBy: "Dr. Nadia Al Farsi",
    },
    {
      id: 2,
      patientId: 2,
      patientName: "Fatima Khalid Al Nahyan",
      markerType: "ca153",
      value: 18,
      unit: "U/mL",
      referenceRange: "<30",
      testDate: getDateString(-14),
      trend: "decreasing",
      previousValue: 25,
      orderedBy: "Dr. Nadia Al Farsi",
    },
    {
      id: 3,
      patientId: 5,
      patientName: "Khalid Ibrahim Al Suwaidi",
      markerType: "psa",
      value: 0.4,
      unit: "ng/mL",
      referenceRange: "<4.0",
      testDate: getDateString(-30),
      trend: "decreasing",
      previousValue: 8.5,
      orderedBy: "Dr. Ahmad Malik",
      notes: "Post-prostatectomy nadir achieved",
    },
  ],
};

// ============================================
// LABORATORY DEMO DATA
// ============================================

export const laboratoryData = {
  orders: [
    {
      id: 1,
      orderNumber: "LAB-2024-001234",
      orderDate: getDateString(0),
      status: 0, // Pending
      patientId: 1,
      branchId: 1,
      orderedBy: "Dr. Sarah Ahmed",
      isUrgent: false,
      totalAmount: 450,
      isPaid: true,
      clinicalNotes: "Annual checkup, routine blood work",
      tests: ["CBC", "BMP", "Lipid Panel", "HbA1c", "TSH"],
    },
    {
      id: 2,
      orderNumber: "LAB-2024-001235",
      orderDate: getDateString(-1),
      status: 1, // Collected
      patientId: 2,
      branchId: 1,
      orderedBy: "Dr. Mohammed Ali",
      collectionDate: getDateString(-1),
      collectedBy: "Lab Tech Aisha",
      isUrgent: true,
      totalAmount: 850,
      isPaid: true,
      clinicalNotes: "Suspected infection, fever 3 days",
      tests: ["CBC with Differential", "Blood Culture", "CRP", "Procalcitonin"],
    },
    {
      id: 3,
      orderNumber: "LAB-2024-001236",
      orderDate: getDateString(-3),
      status: 3, // Completed
      patientId: 3,
      branchId: 1,
      orderedBy: "Dr. Sarah Ahmed",
      collectionDate: getDateString(-3),
      completedDate: getDateString(-2),
      isUrgent: false,
      totalAmount: 350,
      isPaid: true,
      tests: ["Liver Function Tests", "Kidney Function Tests"],
    },
    {
      id: 4,
      orderNumber: "LAB-2024-001237",
      orderDate: getDateString(-2),
      status: 2, // In Progress
      patientId: 4,
      branchId: 1,
      orderedBy: "Dr. Mohammed Ali",
      collectionDate: getDateString(-2),
      isUrgent: false,
      totalAmount: 1200,
      isPaid: false,
      clinicalNotes: "Pre-operative workup",
      tests: ["CBC", "PT/INR", "PTT", "BMP", "Type and Screen", "Urinalysis"],
    },
    {
      id: 5,
      orderNumber: "LAB-2024-001238",
      orderDate: getDateString(0),
      status: 0, // Pending
      patientId: 5,
      branchId: 1,
      orderedBy: "Dr. Nadia Al Farsi",
      isUrgent: true,
      totalAmount: 650,
      isPaid: true,
      clinicalNotes: "Tumor marker follow-up",
      tests: ["PSA", "CEA", "AFP"],
    },
  ],
};

// ============================================
// RADIOLOGY DEMO DATA
// ============================================

export const radiologyData = {
  orders: [
    {
      id: 1,
      orderNumber: "RAD-2024-000456",
      patientId: 1,
      patientName: "Ahmed Hassan Al Maktoum",
      modality: "CT",
      bodyPart: "Chest",
      indication: "Lung cancer staging",
      priority: "Routine",
      status: "Completed",
      orderedBy: "Dr. Nadia Al Farsi",
      orderDate: getDateString(-7),
      scheduledDate: getDateString(-5),
      completedDate: getDateString(-5),
      findings: "Stable 2.5cm RUL mass. No new nodules. No lymphadenopathy.",
      impression: "Stable disease, no evidence of progression",
      reportedBy: "Dr. Radiologist Khan",
    },
    {
      id: 2,
      orderNumber: "RAD-2024-000457",
      patientId: 2,
      patientName: "Fatima Khalid Al Nahyan",
      modality: "MRI",
      bodyPart: "Breast",
      indication: "Post-treatment surveillance",
      priority: "Routine",
      status: "Scheduled",
      orderedBy: "Dr. Nadia Al Farsi",
      orderDate: getDateString(-3),
      scheduledDate: getDateString(2),
    },
    {
      id: 3,
      orderNumber: "RAD-2024-000458",
      patientId: 5,
      patientName: "Khalid Ibrahim Al Suwaidi",
      modality: "X-Ray",
      bodyPart: "Left Wrist",
      indication: "Fall, suspected fracture",
      priority: "Urgent",
      status: "Completed",
      orderedBy: "Dr. Sarah Ahmed",
      orderDate: getDateString(-1),
      completedDate: getDateString(-1),
      findings:
        "Distal radius fracture with dorsal angulation. No intra-articular extension.",
      impression: "Colles fracture, recommend orthopedic consultation",
      reportedBy: "Dr. Radiologist Khan",
    },
    {
      id: 4,
      orderNumber: "RAD-2024-000459",
      patientId: 3,
      patientName: "Mohammed Rashid Al Falasi",
      modality: "Ultrasound",
      bodyPart: "Abdomen",
      indication: "Liver metastasis surveillance",
      priority: "Routine",
      status: "InProgress",
      orderedBy: "Dr. Ahmad Malik",
      orderDate: getDateString(0),
      scheduledDate: getDateString(0),
    },
    {
      id: 5,
      orderNumber: "RAD-2024-000460",
      patientId: 1,
      patientName: "Ahmed Hassan Al Maktoum",
      modality: "MRI",
      bodyPart: "Right Knee",
      indication: "ACL injury evaluation",
      priority: "Routine",
      status: "Completed",
      orderedBy: "Dr. Khalid Al Mansouri",
      orderDate: getDateString(-10),
      completedDate: getDateString(-8),
      findings:
        "Complete ACL tear. Bone bruising lateral femoral condyle. Intact menisci.",
      impression: "ACL rupture, recommend surgical consultation",
      reportedBy: "Dr. Radiologist Khan",
    },
  ],
};

// ============================================
// PHARMACY DEMO DATA
// ============================================

export const pharmacyData = {
  prescriptions: [
    {
      id: 1,
      prescriptionNumber: "RX-2024-005678",
      patientId: 1,
      patientName: "Ahmed Hassan Al Maktoum",
      prescribedBy: "Dr. Sarah Ahmed",
      prescriptionDate: getDateString(0),
      status: "Pending",
      medications: [
        {
          name: "Paracetamol 500mg",
          dosage: "1 tablet",
          frequency: "Every 6 hours as needed",
          duration: "7 days",
          quantity: 28,
        },
        {
          name: "Ibuprofen 400mg",
          dosage: "1 tablet",
          frequency: "Twice daily with food",
          duration: "5 days",
          quantity: 10,
        },
      ],
      notes: "For post-injury pain management",
    },
    {
      id: 2,
      prescriptionNumber: "RX-2024-005679",
      patientId: 2,
      patientName: "Fatima Khalid Al Nahyan",
      prescribedBy: "Dr. Nadia Al Farsi",
      prescriptionDate: getDateString(-1),
      status: "Dispensed",
      dispensedDate: getDateString(-1),
      dispensedBy: "Pharmacist Omar",
      medications: [
        {
          name: "Tamoxifen 20mg",
          dosage: "1 tablet",
          frequency: "Once daily",
          duration: "30 days",
          quantity: 30,
        },
        {
          name: "Calcium + Vitamin D",
          dosage: "1 tablet",
          frequency: "Once daily",
          duration: "30 days",
          quantity: 30,
        },
      ],
      notes: "Hormone therapy continuation",
    },
    {
      id: 3,
      prescriptionNumber: "RX-2024-005680",
      patientId: 3,
      patientName: "Mohammed Rashid Al Falasi",
      prescribedBy: "Dr. Ahmad Malik",
      prescriptionDate: getDateString(-3),
      status: "Dispensed",
      dispensedDate: getDateString(-3),
      medications: [
        {
          name: "Ondansetron 8mg",
          dosage: "1 tablet",
          frequency: "As needed before chemo",
          duration: "30 days",
          quantity: 20,
        },
        {
          name: "Dexamethasone 4mg",
          dosage: "2 tablets",
          frequency: "Day of chemo",
          duration: "30 days",
          quantity: 12,
        },
        {
          name: "Omeprazole 20mg",
          dosage: "1 capsule",
          frequency: "Once daily",
          duration: "30 days",
          quantity: 30,
        },
      ],
      notes: "Chemotherapy supportive care medications",
    },
    {
      id: 4,
      prescriptionNumber: "RX-2024-005681",
      patientId: 4,
      patientName: "Sara Omar Al Ketbi",
      prescribedBy: "Dr. Khalid Al Mansouri",
      prescriptionDate: getDateString(0),
      status: "Pending",
      medications: [
        {
          name: "Celecoxib 200mg",
          dosage: "1 capsule",
          frequency: "Twice daily",
          duration: "14 days",
          quantity: 28,
        },
        {
          name: "Glucosamine 1500mg",
          dosage: "1 tablet",
          frequency: "Once daily",
          duration: "30 days",
          quantity: 30,
        },
      ],
      notes: "For hip osteoarthritis",
    },
  ],
};

// ============================================
// HR & PAYROLL DEMO DATA
// ============================================

export const hrData = {
  employees: [
    {
      id: 1,
      employeeId: "EMP-001",
      fullName: "Dr. Khalid Al Mansouri",
      fullNameAr: "د. خالد المنصوري",
      email: "khalid.mansouri@xenonclinic.ae",
      phone: "+971501234567",
      department: "Orthopedics",
      position: "Senior Orthopedic Surgeon",
      employmentType: "Full-time",
      hireDate: getDateString(-1095), // ~3 years ago
      salary: 65000,
      currency: "AED",
      status: 1, // Active
      managerId: null,
      qualifications: "MD, Fellowship Orthopedic Surgery",
      specializations: ["Joint Replacement", "Sports Medicine", "Trauma"],
    },
    {
      id: 2,
      employeeId: "EMP-002",
      fullName: "Dr. Sarah Ahmed",
      fullNameAr: "د. سارة أحمد",
      email: "sarah.ahmed@xenonclinic.ae",
      phone: "+971501234568",
      department: "Orthopedics",
      position: "Orthopedic Surgeon",
      employmentType: "Full-time",
      hireDate: getDateString(-730), // ~2 years ago
      salary: 45000,
      currency: "AED",
      status: 1,
      managerId: 1,
      qualifications: "MD, Orthopedic Surgery Residency",
      specializations: ["Sports Medicine", "Hand Surgery"],
    },
    {
      id: 3,
      employeeId: "EMP-003",
      fullName: "Dr. Nadia Al Farsi",
      fullNameAr: "د. ناديا الفارسي",
      email: "nadia.alfarsi@xenonclinic.ae",
      phone: "+971501234569",
      department: "Oncology",
      position: "Medical Oncologist",
      employmentType: "Full-time",
      hireDate: getDateString(-547), // ~1.5 years ago
      salary: 55000,
      currency: "AED",
      status: 1,
      qualifications: "MD, Oncology Fellowship",
      specializations: ["Breast Cancer", "Lung Cancer"],
    },
    {
      id: 4,
      employeeId: "EMP-004",
      fullName: "Dr. Ahmad Malik",
      fullNameAr: "د. أحمد مالك",
      email: "ahmad.malik@xenonclinic.ae",
      phone: "+971501234570",
      department: "Oncology",
      position: "Medical Oncologist",
      employmentType: "Full-time",
      hireDate: getDateString(-365),
      salary: 50000,
      currency: "AED",
      status: 1,
      qualifications: "MD, Oncology Fellowship",
      specializations: ["GI Cancers", "Genitourinary Cancers"],
    },
    {
      id: 5,
      employeeId: "EMP-005",
      fullName: "Nurse Aisha Hassan",
      fullNameAr: "الممرضة عائشة حسن",
      email: "aisha.hassan@xenonclinic.ae",
      phone: "+971501234571",
      department: "Nursing",
      position: "Senior Nurse",
      employmentType: "Full-time",
      hireDate: getDateString(-912),
      salary: 15000,
      currency: "AED",
      status: 1,
      qualifications: "BSN, Oncology Nursing Certification",
    },
    {
      id: 6,
      employeeId: "EMP-006",
      fullName: "Omar Khalid",
      email: "omar.khalid@xenonclinic.ae",
      phone: "+971501234572",
      department: "Laboratory",
      position: "Lab Technician",
      employmentType: "Full-time",
      hireDate: getDateString(-456),
      salary: 12000,
      currency: "AED",
      status: 1,
      qualifications: "Medical Laboratory Technology Diploma",
    },
    {
      id: 7,
      employeeId: "EMP-007",
      fullName: "Fatima Al Rashid",
      fullNameAr: "فاطمة الراشد",
      email: "fatima.rashid@xenonclinic.ae",
      phone: "+971501234573",
      department: "Reception",
      position: "Front Desk Coordinator",
      employmentType: "Full-time",
      hireDate: getDateString(-278),
      salary: 8000,
      currency: "AED",
      status: 1,
    },
    {
      id: 8,
      employeeId: "EMP-008",
      fullName: "Pharmacist Omar Hassan",
      email: "omar.hassan@xenonclinic.ae",
      phone: "+971501234574",
      department: "Pharmacy",
      position: "Clinical Pharmacist",
      employmentType: "Full-time",
      hireDate: getDateString(-640),
      salary: 18000,
      currency: "AED",
      status: 1,
      qualifications: "PharmD, Clinical Pharmacy Certificate",
    },
  ],
  payroll: [
    {
      id: 1,
      employeeId: 1,
      employeeName: "Dr. Khalid Al Mansouri",
      month: "2024-12",
      basicSalary: 65000,
      allowances: 5000,
      deductions: 1500,
      netSalary: 68500,
      status: "Processed",
      processedDate: getDateString(-5),
    },
    {
      id: 2,
      employeeId: 2,
      employeeName: "Dr. Sarah Ahmed",
      month: "2024-12",
      basicSalary: 45000,
      allowances: 3000,
      deductions: 1000,
      netSalary: 47000,
      status: "Processed",
      processedDate: getDateString(-5),
    },
    {
      id: 3,
      employeeId: 3,
      employeeName: "Dr. Nadia Al Farsi",
      month: "2024-12",
      basicSalary: 55000,
      allowances: 4000,
      deductions: 1200,
      netSalary: 57800,
      status: "Pending",
    },
  ],
};

// ============================================
// FINANCIAL DEMO DATA
// ============================================

export const financialData = {
  invoices: [
    {
      id: 1,
      invoiceNumber: "INV-2024-001234",
      patientId: 1,
      patientName: "Ahmed Hassan Al Maktoum",
      invoiceDate: getDateString(0),
      dueDate: getDateString(30),
      status: "Pending",
      subtotal: 5000,
      tax: 250,
      discount: 0,
      total: 5250,
      items: [
        {
          description: "Orthopedic Consultation",
          quantity: 1,
          unitPrice: 500,
          total: 500,
        },
        {
          description: "MRI Right Knee",
          quantity: 1,
          unitPrice: 2500,
          total: 2500,
        },
        {
          description: "Physiotherapy Session",
          quantity: 4,
          unitPrice: 500,
          total: 2000,
        },
      ],
      insuranceClaim: "Daman - DAM-2024-001234",
    },
    {
      id: 2,
      invoiceNumber: "INV-2024-001235",
      patientId: 2,
      patientName: "Fatima Khalid Al Nahyan",
      invoiceDate: getDateString(-7),
      dueDate: getDateString(23),
      status: "Paid",
      paidDate: getDateString(-3),
      subtotal: 8500,
      tax: 425,
      discount: 500,
      total: 8425,
      items: [
        {
          description: "Oncology Consultation",
          quantity: 1,
          unitPrice: 800,
          total: 800,
        },
        {
          description: "Chemotherapy Administration",
          quantity: 1,
          unitPrice: 5000,
          total: 5000,
        },
        {
          description: "Laboratory Tests",
          quantity: 1,
          unitPrice: 1200,
          total: 1200,
        },
        {
          description: "Medications",
          quantity: 1,
          unitPrice: 1500,
          total: 1500,
        },
      ],
      insuranceClaim: "Oman Insurance - OIC-2024-005678",
      paymentMethod: "Insurance + Cash",
    },
    {
      id: 3,
      invoiceNumber: "INV-2024-001236",
      patientId: 3,
      patientName: "Mohammed Rashid Al Falasi",
      invoiceDate: getDateString(-14),
      dueDate: getDateString(16),
      status: "Partial",
      paidAmount: 5000,
      subtotal: 15000,
      tax: 750,
      discount: 1000,
      total: 14750,
      items: [
        {
          description: "Chemotherapy Cycle",
          quantity: 1,
          unitPrice: 12000,
          total: 12000,
        },
        {
          description: "Anti-emetics",
          quantity: 1,
          unitPrice: 800,
          total: 800,
        },
        {
          description: "Growth Factor Injection",
          quantity: 1,
          unitPrice: 2200,
          total: 2200,
        },
      ],
      notes: "Payment plan approved - 3 installments",
    },
    {
      id: 4,
      invoiceNumber: "INV-2024-001237",
      patientId: 5,
      patientName: "Khalid Ibrahim Al Suwaidi",
      invoiceDate: getDateString(-1),
      dueDate: getDateString(29),
      status: "Pending",
      subtotal: 1200,
      tax: 60,
      discount: 0,
      total: 1260,
      items: [
        {
          description: "Emergency Consultation",
          quantity: 1,
          unitPrice: 400,
          total: 400,
        },
        {
          description: "X-Ray Left Wrist",
          quantity: 1,
          unitPrice: 350,
          total: 350,
        },
        {
          description: "Cast Application",
          quantity: 1,
          unitPrice: 450,
          total: 450,
        },
      ],
    },
  ],
};

// ============================================
// DENTAL EXTENDED DEMO DATA
// ============================================

export const dentalData = {
  treatments: [
    {
      id: 1,
      patientId: 1,
      patientName: "Aisha Mohammed Al Rashid",
      treatmentDate: getDateString(-7),
      treatmentType: "root_canal",
      tooth: "46",
      status: "completed",
      dentist: "Dr. Yusuf Al Tamimi",
      duration: 90,
      cost: 2500,
      notes: "Successful root canal treatment, permanent filling placed",
    },
    {
      id: 2,
      patientId: 2,
      patientName: "David Lee Johnson",
      treatmentDate: getDateString(-3),
      treatmentType: "filling",
      tooth: "36",
      status: "completed",
      dentist: "Dr. Layla Hassan",
      duration: 45,
      cost: 450,
      notes: "Composite filling, occlusion checked",
    },
    {
      id: 3,
      patientId: 3,
      patientName: "Priya Sharma",
      treatmentDate: getDateString(0),
      treatmentType: "cleaning",
      status: "in_progress",
      dentist: "Hygienist Sara",
      duration: 60,
      cost: 350,
      notes: "Regular prophylaxis and scaling",
    },
    {
      id: 4,
      patientId: 1,
      patientName: "Aisha Mohammed Al Rashid",
      treatmentDate: getDateString(7),
      treatmentType: "crown",
      tooth: "46",
      status: "scheduled",
      dentist: "Dr. Yusuf Al Tamimi",
      cost: 3500,
      notes: "Crown preparation scheduled, post root canal",
    },
  ],
  charts: [
    {
      id: 1,
      patientId: 1,
      patientName: "Aisha Mohammed Al Rashid",
      chartDate: getDateString(-7),
      teeth: {
        "11": { condition: "healthy", notes: "" },
        "12": { condition: "healthy", notes: "" },
        "21": { condition: "healthy", notes: "" },
        "22": { condition: "filling", notes: "Composite filling present" },
        "36": { condition: "healthy", notes: "" },
        "46": {
          condition: "root_canal",
          notes: "RCT completed, crown scheduled",
        },
      },
      generalNotes: "Good oral hygiene, regular checkups recommended",
      createdBy: "Dr. Yusuf Al Tamimi",
    },
  ],
};

// ============================================
// CARDIOLOGY DEMO DATA
// ============================================

export const cardiologyData = {
  ecgs: [
    {
      id: 1,
      patientId: 1,
      patientName: "Ahmed Hassan Al Maktoum",
      testDate: getDateString(-14),
      heartRate: 72,
      rhythm: "Normal Sinus Rhythm",
      prInterval: 160,
      qrsDuration: 88,
      qtInterval: 400,
      axis: "Normal",
      interpretation: "Normal ECG, no acute changes",
      performedBy: "ECG Tech Fatima",
      reviewedBy: "Dr. Cardiology",
    },
    {
      id: 2,
      patientId: 5,
      patientName: "Khalid Ibrahim Al Suwaidi",
      testDate: getDateString(-30),
      heartRate: 68,
      rhythm: "Normal Sinus Rhythm",
      prInterval: 172,
      qrsDuration: 92,
      qtInterval: 420,
      axis: "Normal",
      interpretation: "Normal ECG, minor nonspecific T-wave changes",
      notes: "Pre-operative clearance",
      performedBy: "ECG Tech Fatima",
      reviewedBy: "Dr. Cardiology",
    },
  ],
  echos: [
    {
      id: 1,
      patientId: 5,
      patientName: "Khalid Ibrahim Al Suwaidi",
      testDate: getDateString(-30),
      lvef: 60,
      lvidd: 48,
      lvids: 32,
      wallMotion: "Normal",
      valves: "All valves normal, no regurgitation or stenosis",
      pericardium: "Normal, no effusion",
      interpretation: "Normal echocardiogram",
      performedBy: "Echo Tech Mohammed",
      reviewedBy: "Dr. Cardiology",
    },
  ],
};

// ============================================
// DERMATOLOGY DEMO DATA
// ============================================

export const dermatologyData = {
  skinExams: [
    {
      id: 1,
      patientId: 1,
      patientName: "Ahmed Hassan Al Maktoum",
      examDate: getDateString(-30),
      examType: "Full Body Skin Exam",
      findings:
        "Multiple benign nevi noted. One atypical appearing nevus on right upper back.",
      areas: ["Back", "Arms", "Legs", "Chest"],
      recommendations:
        "Biopsy recommended for atypical nevus. Follow-up in 3 months.",
      performedBy: "Dr. Dermatologist",
    },
    {
      id: 2,
      patientId: 3,
      patientName: "Mohammed Rashid Al Falasi",
      examDate: getDateString(-14),
      examType: "Targeted Exam",
      findings: "Seborrheic keratosis on left temple, benign appearance",
      areas: ["Face"],
      recommendations:
        "No treatment needed, can remove for cosmetic reasons if desired",
      performedBy: "Dr. Dermatologist",
    },
  ],
  biopsies: [
    {
      id: 1,
      patientId: 1,
      patientName: "Ahmed Hassan Al Maktoum",
      biopsyDate: getDateString(-28),
      site: "Right upper back",
      type: "Punch biopsy",
      clinicalDiagnosis: "Atypical nevus",
      pathologyResult: "Mildly dysplastic nevus, completely excised",
      performedBy: "Dr. Dermatologist",
      notes: "No further treatment needed, regular skin checks recommended",
    },
  ],
};

// ============================================
// PEDIATRICS DEMO DATA
// ============================================

export const pediatricsData = {
  growthCharts: [
    {
      id: 1,
      patientId: 10,
      patientName: "Baby Ahmad (3 months)",
      visitDate: getDateString(-7),
      age: "3 months",
      weight: 6.2,
      weightPercentile: 50,
      height: 61,
      heightPercentile: 55,
      headCircumference: 40.5,
      headPercentile: 50,
      notes: "Normal growth, breastfeeding well",
    },
    {
      id: 2,
      patientId: 11,
      patientName: "Sara Al Maktoum (2 years)",
      visitDate: getDateString(-14),
      age: "24 months",
      weight: 12.5,
      weightPercentile: 60,
      height: 87,
      heightPercentile: 65,
      headCircumference: 48,
      headPercentile: 55,
      notes: "Healthy growth pattern, meeting developmental milestones",
    },
  ],
  vaccinations: [
    {
      id: 1,
      patientId: 10,
      patientName: "Baby Ahmad",
      vaccinationDate: getDateString(-7),
      vaccine: "DTaP-IPV-HepB-Hib (Hexavalent)",
      dose: "Dose 2",
      site: "Left thigh",
      lotNumber: "VAC2024-123456",
      expiryDate: getDateString(365),
      nextDue: getDateString(56), // 2 months later
      administeredBy: "Nurse Aisha",
      notes: "No adverse reactions observed",
    },
    {
      id: 2,
      patientId: 10,
      patientName: "Baby Ahmad",
      vaccinationDate: getDateString(-7),
      vaccine: "PCV13 (Pneumococcal)",
      dose: "Dose 2",
      site: "Right thigh",
      lotNumber: "PCV2024-789012",
      expiryDate: getDateString(365),
      nextDue: getDateString(56),
      administeredBy: "Nurse Aisha",
    },
    {
      id: 3,
      patientId: 11,
      patientName: "Sara Al Maktoum",
      vaccinationDate: getDateString(-14),
      vaccine: "MMR",
      dose: "Dose 1",
      site: "Left arm",
      lotNumber: "MMR2024-345678",
      expiryDate: getDateString(180),
      nextDue: getDateString(365), // 12 months later
      administeredBy: "Nurse Aisha",
    },
  ],
  developmentMilestones: [
    {
      id: 1,
      patientId: 10,
      patientName: "Baby Ahmad",
      assessmentDate: getDateString(-7),
      ageAtAssessment: "3 months",
      grossMotor: ["Holds head up", "Pushes up on arms when on tummy"],
      fineMotor: ["Grasps rattle when placed in hand", "Brings hands to mouth"],
      language: ["Coos and makes sounds", "Turns toward sounds"],
      social: ["Smiles at people", "Tries to look at parents"],
      cognitive: [
        "Follows moving objects with eyes",
        "Recognizes familiar faces",
      ],
      overallAssessment: "Meeting all milestones appropriately",
      assessedBy: "Dr. Pediatrics",
    },
  ],
};

// ============================================
// EXPORT ALL DATA
// ============================================

export const allSpecialtyData = {
  orthopedics: orthopedicsData,
  oncology: oncologyData,
  laboratory: laboratoryData,
  radiology: radiologyData,
  pharmacy: pharmacyData,
  hr: hrData,
  financial: financialData,
  dental: dentalData,
  cardiology: cardiologyData,
  dermatology: dermatologyData,
  pediatrics: pediatricsData,
};

export default allSpecialtyData;
